### ISSUE TITLE
Refactor portal storage to allow custom storage implementations per network

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#1039]
With the introduction of beacon and state networks, we need a way to use custom storage implementation based on the network specifications. 

For example, in beacon, we don't use the concept of data radius, we like to have some temporary data and we want to build a `FindContent` response from a range of values from our database. Also, SQLite is enough for beacon and we don't want to use RocksDB.

In our current architecture, we spawn an `OverlayService` implementation per network with a `PortalStorage` [instance](https://github.com/ethereum/trin/blob/44d1f020a4d852f7c0056dcd4bfd797f81bdefbf/trin-history/src/network.rs#L42).
The problem is that `PortalStorage` is specific to the history network, and we would like to swap this implementation with another for beacon and state networks.

To allow this, the most naive approach is to use the repository pattern and create a trait object that would serve as an API interface for the overlay service.  Then, we can have `HistoryStorage`, `BeaconStorage`, and `StateStorage` storage mechanics that would implement this trait. This will move all storage-specific responsibilities to those objects and will encapsulate the logic per network. This will not require refactoring of the overlay service code, because we will use the same API interface as the current `PortalStorage`. 

Because the storage code will grow and to make this implementation feasible and easily maintained, I think we have to extract the storage code from the `portalnet` crate and create a new workspace crate "storage" where all storage implementations will reside.

Here is a list of tasks that we will need to complete to achieve this architecture change:

- [x] 1. Move  `portalnet::types::messages` to `ethportal-api`. (this will allow us to do 2. because of circular dependencies) #1040 
- [x] 2. Extract `portalnet::metrics`  implementations to a separate workspace create. (It makes sense to have a separate crate for the metrics and this will allow us to extract the storage to a separate crate because of circular dependencies) #1043 
- [x] 3. Remove RocksDB #1058 
- [ ] 4. Extract `portalnet::storage` to a separate `storage` workspace crate. (As mentioned above, this is recommended for maintenance concerns and separation of responsibilities.) https://github.com/ethereum/trin/pull/1078
- [ ] 5. Add `HistoryStorage` and `BeaconStorage` implementations with a common portal storage trait. https://github.com/ethereum/trin/pull/1078

**Comment by njgheorghita** [comment]
> I think we have to extract the storage code from the portalnet crate and create a new workspace crate "storage" where all storage implementations will reside.

Maybe I'm wrong here, or misunderstanding. But it seems like we'll only keep the core `Storage` api traits inside this workspace, and then each subnetwork crate (eg `trin-beacon` / `trin-state`) will house their own implementations. Similar to how we treat the `Validator` trait.
