### ISSUE TITLE
Adding implementation to block accumulator with the ability to reorg [WIP]

### ISSUE THREAD

**Issue by chee-chyuan** [ethereum/trin#105]
Currently I have created a separate repo that has a basic accumulator implementation.

https://github.com/chee-chyuan/accumulator_v3

The repo aims to generate test vectors for the master and epoch accumulator.

The following Ssz sedes were used:
master_sede = List[epoch_hash:bytes32, 16777216]
epoch_sede = List[Container[block_hash:bytes32, total_difficulty:uint256],2048]

Randomly selected epoch hashes:
Epoch 1 - 0x73819a452bf470f23c49a9a57386f516292c0f8ec5aca9b14a3ff4ff290ba238.
Epoch 100 - 0xe3195cd7fb347734751e7e5960977473e6f5731c85289a678c9e93b3ebb98d2c
Epoch 200 - 0xfd3998a95f49ef3060557e4ac4492c8e26a784b37ffdaef006e3f97cc51342a5
Epoch 300 - 0x377d0f7e6b416670fb9bf8119e95c8b8ed6fb52a17d27023fafced53f0256035
Epoch 400 - 0xe7a537f748049b61898e062224db09fd59d98fea7b1084f1f2fd4f69ea337772

**Comment by pipermerriam** [comment]
what are the next steps for this?  This is a base component for block header gossip, which is a network that we have not yet built or specified.  You could consider starting into writing a preliminary specification for the header gossip network if you were feeling bold.

**Comment by njgheorghita** [comment]
closing since we're using https://github.com/ethereum/portal-accumulators as our accumulator test vectors
