### ISSUE TITLE
Overlay protocol routing table management

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#109]
Logic for handling [population](https://notes.ethereum.org/8LbisMwtR4yK64SBosb_2g#E2---Population-of-routing-table) and [liveness](https://notes.ethereum.org/8LbisMwtR4yK64SBosb_2g#E3---Liveliness-checks) routing table responsibilities needs implementation in `OverlayProtocol`. 

re: https://github.com/ethereum/trin/pull/103/files#r709322642

**Comment by jacobkaufmann** [comment]
Happy to take this up. May end up splitting this into separate issues for population (adding new peers via `nodes`) and liveness (maintenance of existing peers via `ping`/`pong`).

**Comment by ogenev** [comment]
> Happy to take this up. May end up splitting this into separate issues for population (adding new peers via `nodes`) and liveness (maintenance of existing peers via `ping`/`pong`).

Cool, overlay events are handled now in `trin-core/src/portalnet/overlay.rs`. I feel we have to put the logic for the routing table management in the same file, or probably event better, create new `overlay` folder and split overlay functionality in separate files...
