### ISSUE TITLE
Simplify bridge + add tests

### ISSUE THREAD

**Issue by KolbyML** [ethereum/trin#1100]
> Tbh, I think it would be a worthwhile improvement to extract this logic into a method on BridgeMode. Looks like the only external variable needed is latest_block which could be easily passed in. It would also be good for sanity's sake to add some unit testing to this logic. If you want to address it in a following pr, that's fine by me.

https://github.com/ethereum/trin/pull/1096#discussion_r1455731349

**Comment by njgheorghita** [comment]
@KolbyML I could use a little mindless refactoring so i'll pick this one up

**Comment by KolbyML** [comment]
Sounds good :+1:
