### ISSUE TITLE
New database design

### ISSUE THREAD

**Issue by morph-dev** [ethereum/trin#1157]
We currently store `content-key` and `content-value` as hex text, which occupies twice as much space as needed (each byte uses 2 characters).
We also observe the need to change/update scheme from time to time, and current design doesn't support that.

The goal of this issue is to discuss and design:
- new scheme that uses blobs (instead of text)
- migration from one scheme to another

**Comment by morph-dev** [comment]
## Proposal [2]: Improve Pruning

Pruning currently works like this:

1. After every new content that is inserted, check if we are above storage capacity (+1 query)
2. Lookup for the furthest content id (+1 query)
3. If removing that content brings us below storage capacity (+1 query), don't remove it, update radius and finish pruning
4. Otherwise remove that content (+1 query) and go back to step 2

This leaves us always slightly above storage capacity all the time, resulting in steps 1-3 happening after every insert, and on average it would repeat steps 2-4. So on average ~6 queries after every insert. Query 1 is the most expensive (it has to process every row).

I propose to change pruning logic, by introducing new concepts:
- target capacity - aimed capacity when pruning, e.g. 90% of storage capacity
- pruning capacity - threshold when to start pruning, e.g. 95% of storage capacity
- `pruning_delay` - how many new inserts are needed in order to check if we should prune
- `average_content_size` - `total_content_size / content_count`
  - it will be inaccurate early on (which won't matter much), but it will be very accurate as we get closer to storage capacity

Logic would roughly look like this:
1. After every insert, reduce `pruning_delay` by one and finish if it is not yet zero (otherwise go to 2) (no queries)
2. Check if we are above pruning capacity (1 query). Pruning would look like this:
    1. estimate how many entries we have to remove to reach target capacity and remove that many farthest ones
        - together with query from step 2, this can take only one query (using `DELETE FROM ... ORDER BY ... LIMIT ...`)
        - repeat until we are at least under pruning capacity (we can be above target capacity)
    2. update radius to match current farthest entry that is stored (1 query)
3. Set `pruning_delay` to estimated number of entries that we need to insert in order to get to the storage capacity (100%) (1 query)
    1. to compensate for errors when database is small, don't make it more than current number of stored entries

This would result in not doing any additional queries most of the time, only periodically checking if we should prune (with pruning being most frequent case) and prune larger amount less frequently and more efficiently.

Also, when we report metrics (i.e. on heartbeat), we can update average_content_size and pruning delay for free.

**Comment by ogenev** [comment]
> `average_content_size` - `total_content_size / content_count`

Is this `average_content_size = total_contant_size / content_count` ?

> After every insert, reduce pruning_delay by one and finish if it is not yet zero (otherwise go to 2) (no queries)

If I understand this correctly, the starting `pruning_delay` value would be the `pruning_capacity / average_content_size` ?

**Comment by morph-dev** [comment]
> Is this `average_content_size = total_contant_size / content_count` ?

yes, indeed

> If I understand this correctly, the starting `pruning_delay` value would be the `pruning_capacity / average_content_size` ?

I'm actually thinking something like `min(content_count, total_capacity / average_content_size - content_count)`.
The idea is that:

- it shouldn't be higher than number of items that we currently store (in case our sample is too small for accurate estimates)
- we estimate based on `total_capacity` but we are fine pruning if we are above `pruning_capacity`

**Comment by morph-dev** [comment]
## Proposal [3]: Use Triggers for tracking count and size of all entries.

Currently we either keep track of this in memory (`HistoryStorage`) or make not so cheap queries (`BeaconStorage`) to get this information. Keeping track of it in memory is not very elegant and easy to make coding mistakes, while the query for the total sum of sizes is expensive because it still has to iterate over all items.

Instead, we can use [SQLite triggers](https://www.sqlite.org/lang_createtrigger.html) to keep this information up to date. There will be another table (e.g. usage_stats) that will store total content count and size, and 2 triggers that will update the values on each insert / delete. Something like this (didn't test it):

```sql
CREATE TRIGGER `content_data_insert_trigger`
AFTER INSERT ON `content_data`
FOR EACH ROW
BEGIN
  UPDATE `usage_stats`
  SET content_count = content_count + 1, content_size = content_size + NEW.content_size
  WHERE content_type = :content_type;
END
```

**Comment by morph-dev** [comment]
Everything described here was already implemented and this issue can be closed.
The code is in: [`trin-storage/src/versioned/id_indexed_v1`](https://github.com/ethereum/trin/tree/e66c5c2c0785b6b29a54317dd02afc7e71b55015/trin-storage/src/versioned/id_indexed_v1)
