### ISSUE TITLE
Add project level rust-toolchain.toml

### ISSUE THREAD

**Issue by GrapeBaBa** [ethereum/trin#1199]
Since right now trin required rust 1.75.0, is it better to add a project level rust-toolchain.toml?

**Comment by GrapeBaBa** [comment]
If yes, i would like to make a PR for this.

**Comment by KolbyML** [comment]
Is rust-toolchain.toml a common practice? I wonder what it is for

**Comment by GrapeBaBa** [comment]
> Is rust-toolchain.toml a common practice? I wonder what it's advantages are over our current solution

I got error when build trin a month ago since i used latest rust version, what the current solution in trin? I found several famous projects use a rust-toolchain.toml and don't know if it is a best practice.

**Comment by njgheorghita** [comment]
According to the [docs](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) ... ` This is most often the case for nightly-only software that pins to a revision from the release archives.` 
Given that we're not `nightly-only` and that most of the projects whose structure we "emulate" don't use a `rust-toolchain.toml`, I'd probably lean against including this in our project, until there's an explicit reason to do so.

**Comment by GrapeBaBa** [comment]
@njgheorghita OK.
