### ISSUE TITLE
Why are we receiving so many duplicate offers from the same peer?

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#1221]
`AcceptQueue` [log](https://github.com/ethereum/trin/blob/master/portalnet/src/accept_queue.rs#L61-L63) is very noisy, especially when we don't expect to be receiving many offers for the same content key from the same peer. It's worth investigating to see if the cause for this noisiness is a bug

**Comment by morph-dev** [comment]
I'm not 100% sure (especially with your most recent changes) but I think something like this can happen:

1. `A` receives and accepts offer for the same content from both `B` and `C` (or more)
2. `A` receives content value from `B`, stores it, and offers it to `D`
3. `A` receives content value from `C`, notices that it's actually already stored, logs warning, and offers it to `D` anyway

`D` might have received similar offers from other clients (e.g. `B` or `C`), making things worse for the whole network.

**Comment by njgheorghita** [comment]
Closing this since as long as Fluffy doesn't implement protection against gossiping the same content to the same peer twice, then there doesn't seem to be any feasible way to test this situation (other than an intensive investigation w/ kurtosis & a trin-only network, but that seems unnecessary for the time being)
