### ISSUE TITLE
PortalStorage should delete items in a background "tending" thread

### ISSUE THREAD

**Issue by mrferris** [ethereum/trin#124]
PortalStorage currently will delete items if launched with a smaller capacity, it just won't start doing that until the first `store(...)` is called. 

It should instead do that upon initialization so that the first `store(..)` doesn't take a long time due to large deletions.

**Comment by pipermerriam** [comment]
I would suggest for this to be a separate background "tending" process so that neither initialization, or any call to `store` will hang unnecessarily.
