### ISSUE TITLE
Fails to decrypt message from a new node with same IP/port as a formerly connected node

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trin#146]
I get this when trying to make two instances of the client to talk with each other: 

```
Oct 19 09:22:05.983 DEBUG discv5::socket::recv: Packet decoding failed: HeaderDecryptionFailed
```

I'm using `master` at 77d61ca616

**Comment by ogenev** [comment]
It happens to me from time to time, I'm not sure what is the underlying reason for this, needs to be investigated more. One workaround is to just change the port of the bootnode client and rerun it and then try to make the handshake again.

**Comment by lithp** [comment]
@ogenev ah, nice catch! My previous confidence was misinformed then, I don't know why this is happening

**Comment by pipermerriam** [comment]
A bit more testing. This seems to happen for me even when using a completely new `node-id` and a different port.

bootnode being run locally with this command:

```
trin --external-address "127.0.0.1:9001" --discovery-port 9001
```

node connecting to bootnode being run with:

```
trin --web3-ipc-path /tmp/trin-jsonrpc2.ipc --unsafe-private-key 82a94dafe3cfd2a39f102fbfc0a4f123489a007d6c020f6ae438af6b09ddcd66 --external-address "127.0.0.1:9003" --discovery-port 9003 --bootnodes="-IS4QD-F2XfOAAy5sutz_MHF6pWi2eUT64BK1N9BcozsVcAbRCxB-jqa_vD3fSLxbKH_XNyKgmV2LbRtT-VMxVNl25kBgmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQP-74xWwc1soXHHgqFgSgA4yvGBgMR0qDf_KvJRfryE8oN1ZHCCIyk"
```

**Comment by KolbyML** [comment]
Is this bug still an issue or has it been fixed?
