### ISSUE TITLE
Fix "Unable to initialize bitlist for requested keys" error when trying to accept many items

### ISSUE THREAD

**Issue by carver** [ethereum/trin#1484]
Got this in my logs, and it seems like it shouldn't ever happen:
```
2024-09-25T00:47:52.235808Z ERROR trin_history::events: Error processing portal history request, responding with empty TALKRESP error=Error while building accept message: Unable to initialize bitlist for requested keys. request.discv5.id=aaa81102dc43bd18
```

Error is triggered here:
https://github.com/ethereum/trin/blob/b28beff3e83bc8bdcf7b9cf7bcb2f934bed652f0/portalnet/src/overlay/service.rs#L1057-L1059

The size of the Bitlist is defined by the Accept message here:
https://github.com/ethereum/trin/blob/b28beff3e83bc8bdcf7b9cf7bcb2f934bed652f0/ethportal-api/src/types/portal_wire.rs#L567

So it seems that our accept message only stores up to 8 items. The specs suggest that it should [accept up to 64](https://github.com/ethereum/portal-network-specs/blob/35085002701e4ffad7fb95085c1211157bd32a49/portal-wire-protocol.md#accept-0x07).

I'll open a PR to increase this to 64.

**Comment by carver** [comment]
Tangentially, I noticed a minor Bitlist bug: https://github.com/sigp/ethereum_ssz/pull/33

**Comment by morph-dev** [comment]
It feels like we should add a hive tests for this as well:
- sending 64 keys should work (and they should be available after they are accepted)
- sending 65 should fail

**Comment by KolbyML** [comment]
> It feels like we should add a hive tests for this as well:
> 
> - sending 64 keys should work (and they should be available after they are accepted)
> 
> - sending 65 should fail
> 
> 
> 
> 

I mentioned I would write one in Carvor's fix PR for this issue, for continuity sake.
