### ISSUE TITLE
Use same private keys across runs of trin

### ISSUE THREAD

**Issue by carver** [ethereum/trin#15]
> Eventually, we'd want the ability to use known private keys rather than generating new ones every time, right? aka. something like the `--private-key` flag in the python implementation.

_Originally posted by @njgheorghita in https://github.com/carver/trin/pull/14#discussion_r630849366_

Right, and even if you don't supply keys, maybe we don't want to regenerate them every time, because that would probably cause a lot of churn in which state we store (assuming it's related to our node id). So probably we'd want to save/load from a file, if it's not supplied in a cmd line flag.

**Comment by ogenev** [comment]
Feature supported.
