### ISSUE TITLE
Cannot connect to IPC second running instance of trin

### ISSUE THREAD

**Issue by carver** [ethereum/trin#177]
I haven't done broad testing on this, but here is my setup:

1) Run two copies of trin
```sh
TRIN_INFURA_PROJECT_ID="0" RUST_LOG="debug" cargo run
```
```sh
TRIN_DATA_PATH=/tmp/trin-2 TRIN_INFURA_PROJECT_ID="0" RUST_LOG="debug" cargo run -p trin -- --discovery-port 9001 --bootnodes enrI<SNIP>CCIyg --web3-ipc-path /tmp/trin-jsonrpc-2.ipc
```

2)
- First instance opens IPC at default: `JSON-RPC IPC path: /tmp/trin-jsonrpc.ipc`
- Second instance seems to confirm the IP path, with no warnings: `JSON-RPC IPC path: /tmp/trin-jsonrpc-2.ipc`

3) Test connection:
```py
In [1]: from web3 import Web3

In [9]: w3 = Web3(Web3.IPCProvider("/tmp/trin-jsonrpc.ipc"))

In [10]: w3.isConnected()
Out[10]: True

In [11]: w3.provider.make_request("web3_clientVersion", [])
Out[11]: {'id': 1, 'jsonrpc': '2.0', 'result': 'trin v0.1.0'}

In [12]: w3_2 = Web3(Web3.IPCProvider("/tmp/trin-jsonrpc-2.ipc"))

In [13]: w3_2.provider.make_request("web3_clientVersion", [])

ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by carver** [comment]
This is *not* reproducible with a single instance running at a custom IPC location. I think it has something to do with running two copies simultaneously.

**Comment by carver** [comment]
Wow, I'm stumped. If I re-run this with both instances on custom IPC paths, I can't reproduce it. At this point, I'm not confident that I can reproduce with the original setup.

Unfortunately, I've got some other issue that means that every run is rebuilding, so starting trin twice takes 12 minutes. I think I'm done chasing this down for now, at least until I can run trin without waiting for everything to recompile.

**Comment by njgheorghita** [comment]
this is outdated, since it was created when trin was using a custom ipc server implementation, we now use reth-ipc
