### ISSUE TITLE
Handle an inbound Portal WHOAREYOU

### ISSUE THREAD

**Issue by carver** [ethereum/trin#19]
## Current state

We try to ping a portal node now, but when we get a `whoareyou`, we... maybe try to send the same message back?

```rust
impl TalkReqHandler for ProtocolHandler {
    fn talkreq_response(&self, request: TalkRequest) {
        // Send the same request back to the sender!?
        if self.protocol_sender.send(request).is_err() {
            warn!("sending on disconnected channel");
        }
    }
}
```

## Desired state

Send back a handshake packet: https://github.com/ethereum/devp2p/blob/6eddaf50298d551a83bcc242e7ce7024c6cc8590/discv5/discv5-wire.md#handshake-message-packet-flag--2

Save the session to a simple local list of sessions, for later decryption of messages.

Next up will be to resend the original message, encrypted with the new handshake parameters.

We can skip all the kbucket tracking for now, just a simple list of active sessions is sufficient for this issue.

devp2p should have plenty of reference methods for how to implement this, since it's essentially the same as the base-layer protocol. Maybe it's possible to even use some of the library methods directly?

**Comment by carver** [comment]
@SamWilsn This is next, after #18 is merged. Are you up for taking a look again (now that the base layer session init is working)?

**Comment by SamWilsn** [comment]
Sure, yeah!

**Comment by carver** [comment]
Sweet, #18 is merged :+1:

**Comment by carver** [comment]
@SamWilsn you probably want to pull from master. Now that #21 is merged, you'll see useful logs from the discv5 library with the `RUST_LOG=debug` environment var.

**Comment by SamWilsn** [comment]
Sorry it's taken me a while to come around to this, but we don't actually send the same message back. The `protocol_sender`/`protocol_receiver` channel is to transition between the synchronous world of discv5 to the asynchronous world of trin.

I added a call to `process_requests` in [67f62e564...](https://github.com/quilt/trin/commit/67f62e5642d6beaff06875b4c485bde08c352196), and will take a stab at sending back a handshake message soon.

**Comment by njgheorghita** [comment]
Closing since this is implemented
