### ISSUE TITLE
Error handling: Consider switching from `thiserror` to `anyhow` crate

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#214]
Currently, we use [thiserror](https://docs.rs/thiserror/latest/thiserror/) crate to create different types of errors and return them inside our methods. It seems this way of handling errors adds unnecessary overhead (more boilerplate code) and makes sense when building libraries.

It looks like the [anyhow](https://docs.rs/anyhow/1.0.52/anyhow/) crate provides an easy and idiomatic way of handling errors in rust applications.

This blog post describes well library vs application error handling in Rust:
https://nick.groenen.me/posts/rust-error-handling/#libraries-versus-applications

**Comment by ogenev** [comment]
> 'm not remembering exactly, but @ogenev did you once mention that there is some reason we can't entirely switch all our errors over from `thiserror` to `anyhow`?

I had in mind mainly `OverlayRequestError` in `overlay_service` because we are passing some errors between handlers/channels and I think refactoring them will be a more involving process.

Other than this, I guess we can easily switch to `anyhow` in other parts of the code where the error handling is more encapsulated.

**Comment by njgheorghita** [comment]
Personally, I'd agree with the switch over to `anyhow` but only in the case that it can fully replace `thiserror`. Using two different error handling libraries seems fuzzy and confusing where one should use which one. Though, I guess we're currently already using both of them...

**Comment by njgheorghita** [comment]
Closing - `CONTRIBUTING.md` has been updated with new error guidelines
