### ISSUE TITLE
Use `content_id` inside `OverlayService.find_nodes_close_to_content()`

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#216]
If I'm not misunderstanding things, we should be using `content_id` instead of `content_key` to [calculate distances](https://github.com/ethereum/trin/blob/d5413c58ec55216f266dd68db0d528bb76eb5e39/trin-core/src/portalnet/overlay_service.rs#L882) in https://github.com/ethereum/trin/blob/d5413c58ec55216f266dd68db0d528bb76eb5e39/trin-core/src/portalnet/overlay_service.rs#L882. Right now this throws an error since we cannot `xor` two vectors of different lengths (`node_id` and `content_key`)

I played around with a couple solutions, but didn't find anything suitably simple. If anybody has some ideas, lmk or feel free to take this on. Otherwise I'll pick this back up asap

**Comment by jacobkaufmann** [comment]
It looks like you are right, and that we should be using `content_id` here. Those naming semantics are kind of confusing. I can take a look.

**Comment by njgheorghita** [comment]
Also, if I remember correctly, we are operating under the assumption that each overlay network could use a unique distance function. In the same method, it looks like we're enforcing `xor` for each lookup, but it seems like this is incorrect? (Although functional for the history network which is our primary target. But it seems to me like this should be fixed now rather than later)
https://github.com/ethereum/trin/blob/d5413c58ec55216f266dd68db0d528bb76eb5e39/trin-core/src/portalnet/overlay_service.rs#L887

**Comment by jacobkaufmann** [comment]
I agree that we should fix the distance metric now, but I think we can create a separate issue for it, so I created #218.
