### ISSUE TITLE
Update `Offer` message type to use `ContentKey` type

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#231]
More of a placeholder so I don't lose track of this, but anybody can feel free to pick this one up.

**Comment by Narasimha1997** [comment]
Can you please explain this? I would like to work on this.

**Comment by njgheorghita** [comment]
Hey :wave: - Basically, we need to update the `Offer` message type [here](https://github.com/ethereum/trin/blob/master/trin-core/src/portalnet/types/messages.rs#L530) to use our custom `ContentKey` type [here](https://github.com/ethereum/trin/blob/master/trin-core/src/portalnet/types/content_keys.rs#L49) for its `content_keys` field instead of `Vec<Vec<u8>>`

So, the `Offer` type should look like .. 
```rust
#[derive(Debug, PartialEq, Clone, Encode, Decode)]
pub struct Offer {
    pub content_keys: Vec<ContentKey>,
}
```

**Comment by KolbyML** [comment]
Solved with this PR https://github.com/ethereum/trin/pull/325
