### ISSUE TITLE
Testing uTP protocol

### ISSUE THREAD

**Issue by victor-wei126** [ethereum/trin#232]
See this: https://github.com/ethereum/portal-network-specs/issues/122

**Comment by ogenev** [comment]
I'm currently working on this issue and I'm researching various alternatives.

**Comment by KonradStaniec** [comment]
one minor comment, I would be carful with this https://github.com/meqif/rust-utp/, as I saw that it do some weird things like for example: https://github.com/meqif/rust-utp/blob/main/src/socket.rs#L478. 

Imo it pretty unusual for transport level protocol to do something like sending 3 consecutive duplicated acks and treat it like some kinda request, not to mention in amplifies network traffic unnecessary.

I am not saying this library in necessary all bad, but it probably requires thorough review.

**Comment by ogenev** [comment]
> Imo it pretty unusual for transport level protocol to do something like sending 3 consecutive duplicated acks and treat it like some kinda request, not to mention in amplifies network traffic unnecessary.

Isn't this part of the "Fast retransmit" modification in [TCP](https://www.isi.edu/nsnam/DIRECTED_RESEARCH/DR_HYUNAH/D-Research/fast-retransmit.html)?

**Comment by KonradStaniec** [comment]
yep fast retransmit is pretty standard thing, but the case is it is not triggered intentionally by sending 3 duplicated acks, but it is triggered when 3 duplicated acks are received due to network conditions like packet loss or delays.

**Comment by ogenev** [comment]
> yep fast retransmit is pretty standard thing, but the case is it is not triggered intentionally by sending 3 duplicated acks, but it is triggered when 3 duplicated acks are received due to network conditions like packet loss or delays.

Hm, you are right, I think this is some kind of a hack to deal with packet loss. This is from the library readme:

_"The current implementation is somewhat incomplete, lacking a complete implementation of congestion control. However, it does support packet loss detection (except by timeout)..."_

So I guess we should implement the packet loss detection by timeout by ourselves, does Fluffy have this implemented already?

**Comment by KonradStaniec** [comment]
Yep, we follow reference implementation in that regards. When we send first packet we start a timer based on current calculated timeout, if the timer runs out (packet wont be acket in rto time) we resend oldest packet.  The whole logic starts here https://github.com/bittorrent/libutp/blob/master/utp_internal.cpp#L1147.
