### ISSUE TITLE
Switch STUN client to async

### ISSUE THREAD

**Issue by carver** [ethereum/trin#24]
Follow up to #23

This might mean forking `stunclient`? There is an async method, but it looks old and may not be compatible with new-style futures. I'm not familiar enough with the history of async on rust to know without investigating.

**Comment by sbillig** [comment]
There's a compatibility layer for in futures 0.3.x for using libraries on the old futures 0.1.x: https://rust-lang.github.io/futures-rs/blog/2019/04/18/compatibility-layer.html

or maybe https://crates.io/crates/rustun?

**Comment by carver** [comment]
FWIW, rustun is also what we're using for the server. I don't remember what roadblock I ran into, when trying to use it client-side.

**Comment by njgheorghita** [comment]
Closing since async stun isn't high-priority and this issue has been stale for a while
