### ISSUE TITLE
Re-organize JSONRPC api endpoints

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#273]
https://github.com/ethereum/trin/pull/261#discussion_r833551682

**Comment by njgheorghita** [comment]
@jacobkaufmann I began playing around with this, and wanted to get some thoughts before implementing it all. What do you think about this structure?
```
/// Discv5 JSON-RPC endpoints. Start with "discv5_" prefix
#[derive(Debug, PartialEq, Clone)]
pub enum Discv5Endpoint {
    NodeInfo,
    RoutingTableInfo,
}

/// State network JSON-RPC endpoints. Start with "portalState_" prefix
#[derive(Debug, PartialEq, Clone)]
pub enum StateEndpoint {
    DataRadius,
    FindContent,
    FindNodes,
    LocalContent,
    Ping,
}

/// History network JSON-RPC endpoints. Start with "portalHistory_" prefix
#[derive(Debug, PartialEq, Clone)]
pub enum HistoryEndpoint {
    DataRadius,
    FindContent,
    FindNodes,
    LocalContent,
    Ping,
    RecursiveFindContent,
}

/// Ethereum JSON-RPC endpoints not currently supported by portal network requests, proxied to Infura
#[derive(Debug, PartialEq, Clone)]
pub enum InfuraEndpoint {
    BlockNumber,
}

#[derive(Debug, PartialEq, Clone)]
pub enum Web3Endpoint{
    ClientVersion,
}

#[derive(Debug, PartialEq, Clone)]
pub enum EthEndpoint{
    GetBlockByHash,
}

#[derive(Debug, PartialEq, Clone)]
pub enum EthereumEndpoint {
    Infura(InfuraEndpoint),
    Eth(EthEndpoint),
    Web3(Web3Endpoint),
}

#[derive(Debug, PartialEq, Clone)]
pub enum PortalEndpoint {
    History(HistoryEndpoint),
    State(StateEndpoint),
}

/// Global portal network endpoints supported by trin, including infura proxies, Discv5, Ethereum and all overlay network endpoints supported by portal network requests
/// todo... rewrite docs & add doc to docs/ with endpoints
#[derive(Debug, PartialEq, Clone)]
pub enum TrinEndpoint {
    Discv5(Discv5Endpoint),
    Portal(PortalEndpoint),
    Ethereum(EthereumEndpoint),
}
```

I just wasn't quite sure where `InfuraEndpoint` fit into the scheme you suggested, and I figure it makes sense to just namespace the entire ethereum jsonrpc api together under `EthereumEndpoint` before passing it off to sub namespaces.

**Comment by jacobkaufmann** [comment]
This is essentially what I had in mind. We might differ on `InfuraEndpoint`. I don't think `InfuraEndpoint` should exist at all. Instead, my preference would be to maintain some logic that matches `EthEndpoint` and determines whether to proxy to Infura.

I'm also not sure whether `Web3Endpoint` belongs under `EthereumEndpoint`, or if we should put it under `TrinEndpoint` and remove `EthereumEndpoint`.

The `web3` endpoint is weird to me. In Infura documentation, that endpoint is under Ethereum JSON-RPC methods along with a few `net` endpoints, but in the official Ethereum JSON-RPC spec, it is not.

**Comment by njgheorghita** [comment]
closing since we're not currently targeting `eth_*` endpoint support
