### ISSUE TITLE
Docs: Quick and Easy Testnet Launch

### ISSUE THREAD

**Issue by carver** [ethereum/trin#284]
A lot of the structure is there. It could use some polish: https://github.com/ethereum/trin/blob/c00e99c6b02b9f331cec4a43628eec5cfef7f242/docs/getting_started.md

Also, maybe bump the Getting Started a little higher up the repo readme.

**Comment by njgheorghita** [comment]
I've started working on the outline for a blog that gives a little overview of the portal network, and then goes into the basics for getting setup with trin and requesting content from the testnet. Any thoughts on a blog vs. improving `getting_started.md` vs both? I was thinking to publish it on the snakecharmers blog.

**Comment by carver** [comment]
Yeah, I imagine a blog could give the appropriate context and background, with little snippets of code in between, where the getting_started can mostly give just a series of lines of code to run (and maybe link to the blog post?).
