### ISSUE TITLE
Architecture Review Discussion @ DevConnect

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#296]
Devconnect's coming up soon and will be the first time many of us meet in person. It's an ideal opportunity to review the current architecture of Trin, and establish which design patterns we want to embrace moving forward. This is just an evolving list to record various topics that we'd like to discuss. Everybody is welcome to edit this and add whatever topics they'd like.

# Topics
- [ ] Evaluate logging strategy
- [ ] Evaluate Trin general architecture
- [ ] Extract JSONRPC service from `trin-core`?
  - [ ] How to delegate more logic to overlay crates (i.e. content key derivation)
  - [ ] Bridge node functionality
  - [x] Docs location?
- [ ] Evaluate database strategy
  - [x] Move to just one of rocksdb / sqlite?
    - move to just rocksdb
  - [ ] How to handle a preferred cache of data (which isn't within node's radius)?
  - [ ] `trieDB` location
- [x] Improving `trin-cli` ux
    - Remove trin-cli jsonrpc functionality, in favor of using web3.py
- [ ] Backlog grooming session
- [ ] Style guide review
- [x] Switch to nightly Rust with fixed date?
 - Probably a good idea, we get imports granularity [formatter](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#imports_granularity). Cons are there may be some compiler instability but if we bind to a fixed nightly version, we don't care.
 - Nope - we don't want to become unwittingly reliant on nightly features. Just go through manually and tidy up import statements
 - [x] Remove chain id from history content keys
 - [ ] add client version to enr?

**Comment by jacobkaufmann** [comment]
We can do something similar to the [Lighthouse Book](https://lighthouse-book.sigmaprime.io) for docs.
