### ISSUE TITLE
Inject headers to alpha network from external source

### ISSUE THREAD

**Issue by carver** [ethereum/trin#314]
Extract headers (maybe follow the tip of the mainnet chain) from an execution client, and inject them into a trin client, in a way that offers them to other peers on the network.

TODO:

- [x] Manually generate private keys and node ids to create ~8 nodes spread around the DHT ~evenly (perhaps run with larger than usual buckets? Only if that's easier than running more nodes, which seems a little unlikely)
- [x] make a bridge-splitter daemon that:
  - [x] at launch:
    - [x] runs the ~8 trin nodes, with custom ipc path and port ~~(and data directory?)~~
    - [x] connects to 3rd-party service: infura? alchemy? etc
    - [x] listens for new headers to arrive
  - [x] when a header arrives:
    - [x] generate header content-key and content-value
    - [x] call `portal_historyStore` on all ~8 nodes with the header
    - [x] get the transactions and uncles to build the block body, from 3rd party
    - [x] generate block body content-key and content-value
    - [x] call `portal_historyStore` on all ~8 nodes with the block body
    - [x] get the receipts from 3rd party
    - [x] generate receipts content-key and content-value
    - [x] call `portal_historyStore` on all ~8 nodes with the receipts
- [x] In `trin`, after receiving data via `portal_historyStore`, gossip it to relevant nodes in routing table (with matching radius) -- depends on #313 
  - [x] Propagate the data, even if it's not stored locally
    - [x] First approach: #368 
    - [x] Better approach: Pass content values through with the internal Offer request, instead of using database to respond to Accept.
- [ ] #411 -- Propagate using `portal_historyOffer` instead of `portal_historyStore`
- [ ] Use Recursive-Find-Content to confirm that data gets pushed somewhere out to the network from the bridge

**Comment by carver** [comment]
It's quick to generate node IDs. I wrote a python script that is generating 10k / second using eth-keys. That was plenty to find these node IDs that seem to be evenly spread:
```
0001062699225860d6e114c72cae2517e55291148e1ba0357b3ade6827b3f6dd
20026eccb926ffda3c2556597ad5906d4320970f74823722287903e5ab137fba
4002eb4a0645f4f8f3ea2ea75d8b2df567de5a95d7ce9d9a87f2b2f6aa550e77
600122b84f0c22ab6fa95d9747ae76c4c9d4245a88935535039b1b7d861fd534
800048f38a80df283c6100694566532bbb9fb2c8415877530a6dfb161aecd6aa
a0028507e77ed24028ad319176e71792a8423455cd04a5a01bc21ac2d5b789c1
c0020037f5d2261dc391c9a876addceafe51bb64dd9f739433f515939a121718
e000fa0096ffb84e2a148c22ddaa7fff084cef5fd3e2277213d40a82d88d5492
```
(See the 0, 2, 4, 6... in the upper byte, and 0's in the next bytes)

**Comment by njgheorghita** [comment]
closing since this functionality has been completed, :flamingo: :axe:
