### ISSUE TITLE
Beta Updates

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#318]
- [ ] Review peertest to make sure test suite is thoroughly testing the codebase
- [ ] Enhance testnet metrics reporting
- [ ] Improve logging strategy?
- [ ] Remove `--ignore-checksum` flag from `win-build` ci step. [reference](https://github.com/ethereum/trin/issues/379)

**Comment by carver** [comment]
Based on the name, should this be in the Beta milestone?

**Comment by njgheorghita** [comment]
closing, since this is outdated :flamingo: :axe:
