### ISSUE TITLE
Discord invite in README is invalid or expired

### ISSUE THREAD

**Issue by ryankav** [ethereum/trin#329]
Tried to join the discord channel today but the link in the README is either invalid or has expired.  

<img width="439" alt="Screenshot 2022-05-18 at 17 17 45" src="https://user-images.githubusercontent.com/39402882/169092120-ae69e973-380f-435c-8868-4902008c22db.png">

**Comment by ogenev** [comment]
Hey, thanks for letting us know that the link expired, https://github.com/ethereum/trin/pull/330 should fix it!
