### ISSUE TITLE
Validate accepted state content via Oracle

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#341]
We want to validate the accepted state content via Oracle before storing and gossiping about it.

**Comment by njgheorghita** [comment]
Just wondering if this issue is a bit premature since we don't support the state network yet?

**Comment by njgheorghita** [comment]
Closing, we're still not even really moving at all on the state network, even once we get going, this is quite an obvious feature that we'll want to implement. I really don't think it's worth clogging our issue tracker with this. Happy to discuss if there's any opposition
