### ISSUE TITLE
Why does peertest::launch_peertest_nodes() break the capturing of test output?

### ISSUE THREAD

**Issue by carver** [ethereum/trin#355]
See this PR to play along: #356 

In these three scenarios:
1. remove both `assert!(false);` lines
1. remove second `assert!(false);` line (or really, no change at all)
1. remove first `assert!(false);` line, before the `launch_peertest_nodes()` call

I expect these three outcomes:
1. all tests pass, no log output
2. one test fails, showing `Jun 24 13:41:58.030 DEBUG self_peertest::test: debug log`
3. one test fails, showing the above log, and several more from the launched peers

I actually get these three outcomes:
1. all tests pass, no log output
2. one test fails, showing `Jun 24 13:41:58.030 DEBUG self_peertest::test: debug log`
3. one test fails, no output captured at all

**Comment by njgheorghita** [comment]
looks like this was resolved in #353
