### ISSUE TITLE
`--no--stun` doesn't work for all test cases

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#358]
Adding a `--no-stun` flag allows us to deal with the unstable [find_assigned_ip](https://github.com/ethereum/trin/blob/5a52c9068cd9209b4e7d87a86dada952c9a51f51/trin-core/src/socket.rs#L36) method and send a discv5 request with empty ENR IP address and port.

`Discv5` doesn't add the node in the routing table of the receiver when the ENR address is empty.

This worked fine for now in [self_peertest](https://github.com/ethereum/trin/blob/master/tests/self_peertest.rs) but it prevents us to add new test cases where we expect the test node to be added to the remote peer's overlay routing table.

One possible solution is to try to make the `find_assigned_ip` stable. Any more opinions?

**Comment by ogenev** [comment]
I think another reasonable solution is to depreciate [find_assigned_ip](https://github.com/ethereum/trin/blob/5a52c9068cd9209b4e7d87a86dada952c9a51f51/trin-core/src/socket.rs#L36) and use `127.0.0.1:port` as external socket address in tests.

**Comment by carver** [comment]
> I think another reasonable solution is to depreciate [find_assigned_ip](https://github.com/ethereum/trin/blob/5a52c9068cd9209b4e7d87a86dada952c9a51f51/trin-core/src/socket.rs#L36) and use `127.0.0.1:port` as external socket address in tests.

Yeah, I think forcing an address/port in the test is an option that's worked well-enough, like in:
https://github.com/ethereum/trin/blob/7ba304a08784bbd6ed195d304775657b012365ed/trin-core/tests/overlay.rs#L112-L120

or

https://github.com/ethereum/trin/blob/7ba304a08784bbd6ed195d304775657b012365ed/ethportal-peertest/src/lib.rs#L67-L83

Note that we're not forced to use 127.0.0.1 here, as long as we grab the IP once at the beginning of the test and then reuse it.
