### ISSUE TITLE
Mock the data storage for tests in `overlay_service`

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#365]
Running tests in `trin-core/src/portalnet/overlay_service.rs` cause the creation of a lot of data directories in the default database path. Those folders are persistent and not cleaned after the tests run. 

This issue is also touched on in https://github.com/ethereum/trin/issues/333.

The main cause is `PortalStorage` creation in `build_service` helper method:
https://github.com/ethereum/trin/blob/560102e9fa1fca7f1d1c13791740a054d5f9eda4/trin-core/src/portalnet/overlay_service.rs#L1766

I think mocking the database makes sense here and [mockall](https://crates.io/crates/mockall) is one of the popular crates for this kind of job.

**Comment by jacobkaufmann** [comment]
Closing based on merge of #421
