### ISSUE TITLE
Can we remove the `generate-data.rs` script?

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#366]
iiuc, this is an outdated script from when we first were testing out portal storage. I'd be surprised if there's still a need for this? Can anybody think of a reason to keep this script around? 

https://github.com/ethereum/trin/blob/master/trin-core/src/bin/generate-data.rs

**Comment by mrferris** [comment]
I agree with removing it. I think that something inspired by it could make a useful test in `trin-core/tests`, though.

**Comment by ogenev** [comment]
I'm not using it.
