### ISSUE TITLE
Sunsetting `seed-database.rs`

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#367]
https://github.com/ethereum/trin/blob/master/src/bin/seed-database.rs

This script is actively under use by our testnet nodes every time they boot, to seed headers from the first 10000 blocks. It has been useful for testing data availability, and still might be in the near future. But at some point, I imagine it'll become obsolete.

1. Given that we're about to start pumping data into the network, do we still want to maintain this behavior?
2. There's been discussion about adding some kind of `--is-bootnode` (not a good name) flag that would disable any kind of content transmission. The idea being that bootnodes are only concerned with introducing peers to the network and maintaining a view of the network, and do not need the overhead of storing / propagating content.

**Comment by carver** [comment]
> 1. Given that we're about to start pumping data into the network, do we still want to maintain this behavior?

I can imagine removing it, but probably when our network is much more stable. It's probably still useful to make sure the early headers are seeded. At some point, the network should maintain that data on its own.

> 2\. There's been discussion about adding some kind of `--is-bootnode` (not a good name) flag that would disable any kind of content transmission.

Maybe sufficient to use really tiny data limits?

**Comment by njgheorghita** [comment]
Commenting here that at devcon we re-evaluated this and decided to remove it now that we have the bridge and concluded that responsibility for data availability should be isolated to a single piece of architecture
