### ISSUE TITLE
Propagating content that's not in the DB

### ISSUE THREAD

**Issue by carver** [ethereum/trin#368]
Currently, Offer/Accept requires the data to be in the database. There is at least one situation where we want to offer content that may not be in the local database, like with the bridge node(s).

The code that makes the offer and handles the accept is decoupled, so it's not straightforward to hold onto the values in a variable between the two steps, without the database. Currently, the best idea I have is to keep an LRU cache of recently used content. Then we could serve an `Accept` from the cache. It's a little awkward that it's *possible* to offer the content and then have it revoked by the LRU, but I think we could come up with configurations that make that chance vanishingly small in the short time between offer & accept.

As a bonus, having a general LRU cache is something we've occasionally talked about for other cases (like helping the network by storing really hot data outside of your radius). So it might have side benefits.

Side note: the bridge currently uses `portal_historyStore`. Maybe we should make a distinct `portal_historyOfferValue` endpoint that accepts the value to send, rather than add propagate as a sequential step after storing?

**Comment by ogenev** [comment]
What are all use cases for a bridge node? Is it a node that is only gossiping data that is provided from an outside source or it can be also a node that is "not externally controlled" and is expected to always accept any content from any peer of the network and propagate it?

> Maybe we should make a distinct portal_historyOfferValue endpoint that accepts the value to send, rather than add propagate as a sequential step after storing?

Could you elaborate more on this, not sure if I understand what you mean?

> What do you think @ogenev ?

I think it is a good idea to use an LRU cache but I'm not sure if we need to implicitly require all nodes to store data in LRU if it is outside of their radius.

When we gossip the content, we filter from the overlay routing table the nodes which are interested in the content (looking at their radius) so it is expected most of the time, that the offered data match the peer radius.

If I understand the use cases for a bridge node correctly, here is how I'm imagining this to work:

1. Implement LRU cache in portal storage ( we can enable LRU as default behavior or we can use a CLI flag to trigger it?).
2. Check the LRU cache (if it is available?) if the content is not in the db on ACCEPT handling.
3. Add json-rpc endpoint that stores content in LRU only or LRU and db (if it is in radius)?

Then we can use the new endpoint in combination with `portal_historyOffer` to propagate the content. However, this will not work if we want the node to be `unsupervised` as part of the network and gossip about all offered content.

**Comment by carver** [comment]
> What are all use cases for a bridge node?

The primary use cases I've got for it are both about injection. We want to inject new data from the execution network into the portal network, and we want to inject old data (possibly patching up old data that has been dropped).

> Is it a node that is only gossiping data that is provided from an outside source or it can be also a node that is "not externally controlled" and is expected to always accept any content from any peer of the network and propagate it?

The first is the goal, and *not* the 2nd. In my models, the bridge node will be configured to have very little storage capacity. It will focus its efforts on pushing data to peers instead.

> > Maybe we should make a distinct portal_historyOfferValue endpoint that accepts the value to send, rather than add propagate as a sequential step after storing?
> 
> Could you elaborate more on this, not sure if I understand what you mean?

It was a little bit of a tangent. Basically trying to decide how reasonable it is that the bridge node is called with `portal_historyStore`, but doesn't really care if the data is stored (only that it is propagated to peers). Other callers to `portal_historyStore` presumably do care that the data gets stored to disk, and do not care if it's propagated to peers (although I can't think of a reason yet why they would object to it being propagated).

I'll drop it for now, there are bigger issues to resolve.

> 
> > What do you think @ogenev ?
> 
> I think it is a good idea to use an LRU cache but I'm not sure if we need to implicitly require all nodes to store data in LRU if it is outside of their radius.

Right, it just ended up being the easiest way to implement it (see #369 ), and it has the benefit mentioned next...

> When we gossip the content, we filter from the overlay routing table the nodes which are interested in the content (looking at their radius) so it is expected most of the time, that the offered data match the peer radius.

Right, except for the POKE-back mechanism? That concept has evolved a lot, but there was at least one version where we were ignoring radius for it.

There are situations (like the state root) where it might be nice to have it broadly available, even when it wouldn't normally be in a peer's radius. This benefit is usually short-lived, so an LRU is sufficient.

> 
> If I understand the use cases for a bridge node correctly, here is how I'm imagining this to work:
> 
>     1. Implement LRU cache in portal storage ( we can enable LRU as default behavior or we can use a CLI flag to trigger it?).

👍🏻 

> 
>     2. Check the LRU cache (if it is available?) if the content is not in the db on ACCEPT handling.

👍🏻 (these ^ two are implemented in #369 )

>     3. Add json-rpc endpoint that stores content in LRU only or LRU and db (if it is in radius)?

This doesn't require any code changes, based on #369 -- which will automatically push the content into the LRU if it doesn't fit in the DB.

> Then we can use the new endpoint in combination with `portal_historyOffer` to propagate the content. However, this will not work if we want the node to be `unsupervised` as part of the network and gossip about all offered content.

I think a simpler approach will be to add a propagate call to the end of `portal_historyStore` handling. Since `portal_historyOffer` seems to assume that the content is already present in the DB.

So after merging #369, and adding a propagate call to the end of `portal_historyStore`, then I believe we will be ready to do bridge content injection in the Alpha network.

**Comment by carver** [comment]
Just to brainstorm a very different solution: instead of relying on the database to serve up offered (and accepted) data, we could include the values in the Request::Offer and keep passing the values along until the Accept is received.

I feel less confident in the structure of that code, so maybe that is easy, but I'd love some help navigating the code for that.

If we *don't* go that direction, then I think it would be best to merge something like #383 for clarity.
