### ISSUE TITLE
Warn: WHOAREYOU already sent

### ISSUE THREAD

**Issue by mrferris** [ethereum/trin#393]
I sometimes get multiple of these errors when running trin when `TALKREQ` messages are being sent/received by the `discv5` library: 

```Jul 30 15:09:31.314  WARN discv5::handler: WHOAREYOU already sent. Node: 0xbd09..3935, addr: 65.108.42.174:9129```

**Comment by ogenev** [comment]
Could you elaborate on how this can be replicated? When this issue appears, is it when you run local nodes or when you talk to remote bootnodes? Which portal messages trigger this warning?
