### ISSUE TITLE
Automatically derive TreeHash trait for all Accumulator objects

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#398]
Conversation started [here](https://github.com/ethereum/trin/pull/385#pullrequestreview-1054461338).

Automatically deriving the `TreeHash` trait resulted in invalid tree root hashes for `HistoricalEpochs` and `EpochAccumulator` in the [accumulator code](https://github.com/ethereum/trin/blob/master/trin-core/src/types/accumulator.rs), so they were manually implemented instead. It would be preferable (and would result in less clutter) if we could figure out why the automatically derived traits were not compatible and find a way to use them &/or understand why we can't use them.

**Comment by KolbyML** [comment]
Issue is resolved since this PR https://github.com/ethereum/trin/pull/488 removed ``EpochAccumulator`` and PR https://github.com/ethereum/trin/pull/464 ended up removing ``HistoricalEpochs`` no other sections of code don't automatically derive ``TreeHash``. Hence these 2 PR's solved this issue.
