### ISSUE TITLE
Refactor DB utils

### ISSUE THREAD

**Issue by jacobkaufmann** [ethereum/trin#407]
The functions in [`trin-core/src/utils/db.rs`](https://github.com/ethereum/trin/blob/c07fce832ce735faa346d932d996833869cf9b9b/trin-core/src/utils/db.rs) do not behave the way that a caller would expect. For instance, `get_data_dir` returns a `PathBuf` but may also create a directory. `setup_temp_dir` returns a `TempDir` but also sets an environment variable (which is used in `get_root_path`).

These functions should be free of side effects and pure to the extent possible.

**Comment by KolbyML** [comment]
Closing this cause doing it would increase code complexity. For example when getting the directory we would have to call ``fs::create_dir_all`` everywhere we call  ``get_data_dir`` so they are pretty codependent. Also this saves us from having to call ``fs::create_dir_all`` multiple times through the code which helps with readability as there is less cluter.

The same codependence case applies with setup_temp_dir and setting the enviroment variable

If anyone has a clear good reason or thinks they can make a beneficial change we can reopen it.
