### ISSUE TITLE
[Windows]`A socket operation encountered a dead network` while running peertest

### ISSUE THREAD

**Issue by mrferris** [ethereum/trin#425]
The problem: When I run peertest on a Windows Server 2019 VM in Azure, it fails with `Could not serve from IPC path /tmp/ethportal-peertest-buddy-1.ipc: Os { code: 10050, kind: NetworkDown, message: “A socket operation encountered a dead network.” }`.

The error is being thrown when [calling `uds_windows::UnixListener::bind`](https://github.com/ethereum/trin/blob/8a9bb83a416aefbd0d095baa9346774d5ee97704/trin-core/src/jsonrpc/service.rs#L117) in the JSON RPC service. 

Our CI currently also runs Windows Server 2019 and succeeds with the same IPC path. I'm not sure what the difference is between these machines, or whether there's a `enable_unix_domain_sockets` flag somewhere in Windows, or if Azure disables this. 

 I've tried many modifications of the IPC path to be more windows-friendly to no avail. I haven't found anything relevant while googling yet. Posting here in case anyone has any ideas/relevant docs in the meantime.

**Comment by ogenev** [comment]
I would suggest switching to Windows Server 2022, as 2019 is not far away from the end of the Mainstream Support cycle (end of 2023).

**Comment by njgheorghita** [comment]
closing since we do not currently support windows
