### ISSUE TITLE
Log deserialized ENR for boot nodes

### ISSUE THREAD

**Issue by jacobkaufmann** [ethereum/trin#430]
In #387 I [removed a log](https://github.com/ethereum/trin/pull/387#discussion_r957744775) that contained the boot node IP address and mistakenly thought that info was covered by other logs. We should add this log back, and preferably in a nicely formatted way.

**Comment by carver** [comment]
Maybe the preferred solution here is to log both the encoded ENR and the IP/port in the log that starts like "About to spawn History Network with boot nodes" (currently in `trin-history/src/lib.rs`). Currently it's just showing the encoded version.
