### ISSUE TITLE
Invalid message encoding for Portal Accept message

### ISSUE THREAD

**Issue by kdeme** [ethereum/trin#473]
I've noticed invalid Portal protocol `Accept` messages. (Perhaps other responses might have such issue too)

While trying to offer content on the network, I received bogus data where I would expect a proper `Accept` response. Raw bytes received: `7554502072657175657374206572726f723a2043616e27742066696e6420454e5220696e206f7665726c617920726f7574696e67207461626c65206d61746368696e672072656d6f7465204e6f646549643a203078393037392e2e66666663`

The response I'm getting fails on the very first step, decoding the enum value for the Offer response.
The raw bytes I'm getting returned are always the same, which sounded weird, so I tried converting to ASCII, which results in:
`uTP request error: Can't find ENR in overlay routing table matching remote NodeId: 0x9079..fffc`

Which is an actual internal error from: https://github.com/ethereum/trin/blob/4cdea092f2c56f21815c5995ea956b02f31c85ed/trin-core/src/portalnet/overlay_service.rs#L529

This error appears to be propagated all the way to actually sending of the data: 
https://github.com/ethereum/trin/blob/4cdea092f2c56f21815c5995ea956b02f31c85ed/trin-core/src/portalnet/overlay_service.rs#L841 and I think further to https://github.com/ethereum/trin/blob/a9faaee8d4f0148b1b7603df38ee002e31e6cc86/trin-core/src/portalnet/overlay.rs#L195 and https://github.com/ethereum/trin/blob/a9faaee8d4f0148b1b7603df38ee002e31e6cc86/trin-history/src/events.rs#L31?
Not completely sure of the flow of data here as I didn't fully investigate, but it doesn't seem right.

**Comment by njgheorghita** [comment]
this bug was resolved in #475
