### ISSUE TITLE
Pair with a Consensus Layer light client for header canon verification

### ISSUE THREAD

**Issue by carver** [ethereum/trin#477]
Post-merge, the cleanest way to validate that a header is in the canonical chain is to ask a Consensus Layer client. Naturally, we would want to use a light client, to minimize the computational overhead.

Rough target:
- Run a CL light client alongside trin, either:
  1. Use lighthouse, bundle it into the trin release, to run the light client alongside trin in another process
  2. Use another client, like lodestar
      - Make CL client connection config a required part of launch
      - Document how to install & run lodestar as part of trin setup
- When verifying headers post-merge, ask the CL client whether header is canonical
- Gossip the beacon/consensus header alongside the execution header in order to ask ^ (the light client probably cannot quickly answer if an arbitrary execution header is canonical)

TODOs include:

- [ ] https://github.com/ethereum/portal-network-specs/issues/172
- [ ] include the consensus header as proof when gossiping execution header
- [ ] ask lodestar to build a custom light client API for asking "is this consensus header (hash?) canonical" (can skip if lighthouse agrees)
- [ ] ask lighthouse to build a custom light client API for asking "is this consensus header (hash?) canonical"
- [ ] try to standardize ^ as a standard light-client API
- [ ] bundle light client with trin, as much as possible
- [ ] PR to ask whether header is canon
- [ ] PR to validate whether header is canonical, when receiving a new header

**Comment by njgheorghita** [comment]
Closing this since it's outdated, we do have a bundled light client, and we're now using the beacon light client network to verify header canonical-ness.
