### ISSUE TITLE
No standard discovery port

### ISSUE THREAD

**Issue by perama-v** [ethereum/trin#487]
## Problem description

Looking at ports used on the portal network I see two issues:
### 1. Clash with beacon chain
The port used by Trin clashes with the discovery port on beacon chain clients.
This means that by default there will be clashes if users have a beacon client running. This may become annoying if beacon light clients are coupled somehow with portal clients.

### 2. No standard portal network port
Users following generic setup instructions may have to configure port-related settings. If there is
a standard port, these instructions can be cross-client.

## Possible resolution
Decide on a discovery port to converge on for the Portal Network.

Example default ports.
| Client | Network | Port |
| - | - | - |
| Trin, Ultralight | portal | 9000 | 
| Fluffy | portal | ~~?~~ 9009 | 
| Teku, Nimbus, Lodestar, Lighthouse | consensus | 9000 |
| Prysm | consensus | 13000/12000 |
| Geth, Nethermind, Erigon, Besu | execution | 30303 |

**Comment by ogenev** [comment]
Fluffy is on 9009. I agree that we should move away from using 9000 as the default.

**Comment by pipermerriam** [comment]
relevant: https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

**Comment by perama-v** [comment]
Nice, no clashes for 9009 on the wiki
