### ISSUE TITLE
Verify Advertise messages against state root block headers

### ISSUE THREAD

**Issue by carver** [ethereum/trin#51]
Peers should verify the proposed state received in an [`Advertise`](https://github.com/ethereum/stateless-ethereum-specs/blob/master/state-network.md#advertise-0x07). One important part of the verification is that the advertised state has the same state root as defined by a header.

A few unresolved items come up:
- Advertise sends a list of hashes, but doesn't explicitly claim a state root. That leaves the receiving peer to guess and check all the hashes against the header state roots, I suppose
- Ultimately we want to have access to the headers using a gossip network adjacent to the state network. For now, we might just poll Infura for updates to the header chain.

Maybe we should consider modifying the `Advertise` message. Some options that come to mind:
- to include a new entry with the new state root (which ought to be a duplicate with one of the hashes, or maybe we exclude it from the hash list
- make it required that the first hash sent with `Advertise` is the new state root
- include the header hash that the new state is generated in

Also, how frequently can we poll for the latest header, using a free Infura (or Alchemy) account? (If it's continuous all month? If it's only running for ~3 hours a day?)

**Comment by njgheorghita** [comment]
Closing since advertise messages are no longer in the spec, and validation of data is being tracked in the alpha net milestone
