### ISSUE TITLE
Mark peertest binary as deprecated

### ISSUE THREAD

**Issue by perama-v** [ethereum/trin#516]
### Description

The `peertest` crate is used by tests in CI. Running the crate as a binary is not actively supported. 

### Resolution
Documentation in the following places should be updated to reflect this:
- `./ethportal-peertest/README.md` 
- `./docs/contributing.md`
- `./ethportal-peertest/src/main.rs`

**Comment by njgheorghita** [comment]
closing since it has been addressed and nowhere in the repo do we reference peertest as being a standalone executable
