### ISSUE TITLE
Handle unwraps when launching json-rpc server

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#534]
Handle unwraps when launching json-rpc server [here](https://github.com/ethereum/trin/blob/7c475988d20bfe2d3461b5bfe1b812647dea8d69/src/lib.rs#L164) and [here](https://github.com/ethereum/trin/blob/7c475988d20bfe2d3461b5bfe1b812647dea8d69/src/lib.rs#L176).

**Comment by e3243eric** [comment]
Looks like this was fixed.

**Comment by ogenev** [comment]
Fixed by https://github.com/ethereum/trin/pull/562.
