### ISSUE TITLE
Replace `trin-core` content key types with `ethportal-api` types

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#536]
Replace all content key types used in `trin-core` with types from the `ethportal-api` crate.

This includes removing the helper method here:
https://github.com/ethereum/trin/blob/7c475988d20bfe2d3461b5bfe1b812647dea8d69/trin-history/src/jsonrpc.rs#L281

**Comment by KolbyML** [comment]
This PR resolves this issue right https://github.com/ethereum/trin/pull/598 ? If so we can close this issue
