### ISSUE TITLE
ethportal-api: Add `is_unknown` method to `HistoryContentItem` and `HistoryContentKey`.

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#538]
As Jacob mentioned:

_it might be worth adding a method to HistoryContentItem like is_unknown given that now the conversion from a byte vector never fails. with such a method, you would be able to short-circuit your logic without doing a match if you require a valid content item. ultimately, I would prefer that we find some way to remove the Unknown variant while still getting the behavior we want from jsonrpsee. The same goes for HistoryContentKey._

**Comment by jacobkaufmann** [comment]
IMO we should skip the `is_unknown` method and remove the `Unknown` variant from the enum. it doesn't make sense to me to maintain logic to handle invalid data if we can reject it at the RPC layer with an informative error for the requestor.

**Comment by ogenev** [comment]
> IMO we should skip the `is_unknown` method and remove the `Unknown` variant from the enum. it doesn't make sense to me to maintain logic to handle invalid data if we can reject it at the RPC layer with an informative error for the requestor.

My reasoning for adding the `Unknown` type is the case where we want to have a view of the received content, whether it is valid or not.

 For example:

```rust
// We don't want to panic here if the content item is unknown because we may want to
// check the content item value for debugging or tests.
let content_item = client.local_content(content_key).await.unwrap() 
```

However, I don't strongly believe in this use case's viability.

**Comment by jacobkaufmann** [comment]
yea, I would rather not have to check validity if it can be done automatically at the decoding stage. my assumption is that there is some way to test for a specific error message where we expect decoding to fail for invalid data.

one other thing, which I'm not sure about, is whether a value of `0x0` would be decoded as `Unknown("0x0")`, where it should be an `Option::None` value. this is something that I encountered in #504.

**Comment by perama-v** [comment]
> IMO we should skip the `is_unknown` method and remove the `Unknown` variant from the enum. it doesn't make sense to me to maintain logic to handle invalid data if we can reject it at the RPC layer with an informative error for the requestor.

I agree with this. 

The situation of having Unknown content is a state of error. When included as a variant with non-error variants, a caller receives a mixed type (error and non-error). 

The rationale for the Unknown variant is to preserve the data behind an unknown type for debugging purposes. This is indeed valuable but could be provided in an error variant containing all necessary valuable debug information. 

```rs
enum ErrorKind {
    // Enum variant containing addressable members
    UnknownContent { bytes: Vec<u8>, network: String },
}
```
My suggestion would be something like:


```rs

mod test {
    use thiserror::Error;

    #[derive(Error, Debug)]
    pub enum ContentError {
        #[error("could not build content from bytes")]
        UnknownContent { bytes: Vec<u8>, network: String },
    }

    #[test]
    fn type_err_with_debug_info() {
        let input = "0x0124";
        let content = match input {
            "0x0123" => Ok(input), // E.g., create HistoryContentKey here
            _ => Err(ContentError::UnknownContent {
                bytes: input.as_bytes().to_owned(),
                network: "history".to_string(),
            }),
        };
        match content {
            Ok(_) => {} E.g., use HistoryContentKey here
            Err(ContentError::UnknownContent { bytes, network }) => { 
                // Use bytes/network for debugging here.
                println!("Unknown content {bytes:?} from {network}")
            }
        }
    }
}

```

Prints
```console
running 1 test
Unknown content [48, 120, 48, 49, 50, 52] from history
test jsonrpc::test::type_err_with_debug_info ... ok
```

**Comment by ogenev** [comment]
> The rationale for the Unknown variant is to preserve the data behind an unknown type for debugging purposes. This is indeed valuable but could be provided in an error variant containing all necessary valuable debug information.

I'm on board for this change :+1: .
