### ISSUE TITLE
ethportal-api: Update `NodeId` type

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#539]
Right now we have our own custom type for NodeId in `ethportal-api`:

https://github.com/ethereum/trin/blob/7c475988d20bfe2d3461b5bfe1b812647dea8d69/ethportal-api/src/types/discv5.rs#L11

Instead of this, I think it is more robust if we wrap the `NodeId` type over  `discv5::NodeId` and implement all necessary traits to the newtype.

**Comment by KolbyML** [comment]
I will work on this if nobody else is
