### ISSUE TITLE
Refactor hacky errors in `trin-core/portalnet/storage`

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#540]
Errors [here](https://github.com/ethereum/trin/blob/7c475988d20bfe2d3461b5bfe1b812647dea8d69/trin-core/src/portalnet/storage.rs#L355) and [here](https://github.com/ethereum/trin/blob/7c475988d20bfe2d3461b5bfe1b812647dea8d69/trin-core/src/portalnet/storage.rs#L496) are hacks to get around the fact that rusqlite doesn't support returning a custom error type.

**Comment by njgheorghita** [comment]
I was just doing some work w/ this code in https://github.com/ethereum/trin/pull/549 - and there didn't really seem any obvious solutions to me besides returning the `rusqlite::Error`. It seems to me that the `InvalidParameterName` does not make perfect sense in this scenario, but it also seems to be good enough imo. What are you looking for w/ this refactor?

**Comment by ogenev** [comment]
I don't have a strong opinion if we need to fix this or leave it as it is.
