### ISSUE TITLE
ethportal-peertest: Use `jsonrpsee` ipc client instead of our custom client implementation in peertest scenarios

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#541]
We can get rid of some boilerplate code by replacing our custom json-rpc client implementation in `ethportal-peertest` scenarios with a client from the jsonrpsee framework. 

Here is an example scenario of how we can leverage the jsonrpsee client:
https://github.com/ethereum/trin/blob/master/ethportal-peertest/src/scenarios/paginate.rs

**Comment by mattsse** [comment]
fyi:
 https://github.com/paradigmxyz/reth/tree/main/crates/rpc/ipc

**Comment by ogenev** [comment]
> fyi: https://github.com/paradigmxyz/reth/tree/main/crates/rpc/ipc

We are using it at https://github.com/ethereum/trin/tree/master/rpc, thanks for the excellent work! :heart: .

**Comment by njgheorghita** [comment]
closing as this has been implemented
