### ISSUE TITLE
`ethportal-api` tests don't build

### ISSUE THREAD

**Issue by perama-v** [ethereum/trin#557]
### Description

Tests in `ethportal-api/src/types/content_key.rs` do not run, causing multiple errors of the kind:
```
  --> ethportal-api/src/history.rs:14:1
   |
14 | #[rpc(client, server, namespace = "portal")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `RpcModule` in `jsonrpsee`
   |
```
and
```
error[E0412]: cannot find type `RpcModule` in crate `jsonrpsee`
 --> ethportal-api/src/discv5.rs:6:1
  |
6 | #[rpc(client, server, namespace = "discv5")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `jsonrpsee`
  |
```
### Explanation

It seems that this is likely caused by an omitted feature in the `Cargo.toml`.

```
jsonrpsee = {version="0.16.2", features = ["macros"]}
```

**Comment by perama-v** [comment]
This issue also appears when using `ethportal-api = "0.1.4"` in external crates (in Glados, where `0.1.3` is ok).

**Comment by ogenev** [comment]
How do you run the tests? Running `cargo test --workspace` works fine on trin.

If you use `cargo test -p ethportal-api` do not forget the `--all-features` flag: `cargo test -p ethportal-api --all-features`

**Comment by perama-v** [comment]
Ok, I did not know about `--all-features`. So the crate builds fine with `cargo test -p ethportal-api --all-features`

It does seem odd to have the base crate not build without specific features enabled. For example, using `ethportal-api = "0.1.4"` as a crate dependency in Glados does not work.

**Comment by perama-v** [comment]
The context for encountering this problem was updating and running an individual test case (`ethportal-api/src/types/content_key.rs`) in an IDE. Previously this was possible, but now this triggers the above errors. 

So while we have the ethportal-api crate default as follows:
```toml
[features]
default = ["client"]
client = ["jsonrpsee/client", "jsonrpsee/async-client"]
server = ["jsonrpsee/server"]
```
It does not seem that the default is sufficient to build

**Comment by perama-v** [comment]
That is to say the `client` feature: 

```
cargo test -p ethportal-api --features client
```
Triggers the error (and is the default feature).

**Comment by ogenev** [comment]
I see what is the problem, ok, let's remove the features from `ethportal-api` and add the dependencies in jsonrpsee, I don't really see any benefits at this point to have features in `ethportal-api`, only complicates things.

We will release a new version and yank the oldest.

**Comment by perama-v** [comment]
Ok, as in:
```toml
jsonrpsee = {version="0.16.2", features = ["macros", "client", "async-client", "server"]}
```

**Comment by ogenev** [comment]
> Ok, as in:
> 
> ```toml
> jsonrpsee = {version="0.16.2", features = ["macros", "client", "async-client", "server"]}
> ```

yeah

**Comment by perama-v** [comment]
Ok #558 now contains these changes
