### ISSUE TITLE
Deprecate `trin-cli`

### ISSUE THREAD

**Issue by perama-v** [ethereum/trin#573]
### Description

The `trin-cli` was previously used to initiate sending a message from one Trin client to another. 
It is no longer actively maintained or used

### Solution

Either:
- Mark the `trin-cli` crate as deprecated
- Remove the `trin-cli` crate

**Comment by njgheorghita** [comment]
We discussed this today & decided that it's worth investigating whether or not we should bring `trin-cli` back to life...
- A functional/extendable cli utility can improve the workflow
- `trin-cli` is fairly useful when interacting with testnet nodes
- We should be able to leverage `ethportal-api` jsonrpsee client functionality to simplify the existing `trin-cli` logic

Therefore...
This issue remains valid. But, the solution should be to `"Mark the trin-cli crate as deprecated"`, and remove it from our documentation. 

However, if anybody finds some time, it's worth a day/two to investigate whether we can simplify the existing code here & revive `trin-cli` in a functional, useful manner.

Possible sources of inspiration 
- https://github.com/AgeManning/discv5-cli
- ...

**Comment by Tirthnp** [comment]
I would like to attempt doing this one :)

**Comment by ogenev** [comment]
> I would like to attempt doing this one :)

Sure :100: , let us know if you have any questions.

**Comment by KolbyML** [comment]
> We discussed this today & decided that it's worth investigating whether or not we should bring `trin-cli` back to life...
> 
> * A functional/extendable cli utility can improve the workflow
> * `trin-cli` is fairly useful when interacting with testnet nodes
> * We should be able to leverage `ethportal-api` jsonrpsee client functionality to simplify the existing `trin-cli` logic
> 
> Therefore... This issue remains valid. But, the solution should be to `"Mark the trin-cli crate as deprecated"`, and remove it from our documentation.
> 
> However, if anybody finds some time, it's worth a day/two to investigate whether we can simplify the existing code here & revive `trin-cli` in a functional, useful manner.
> 
> Possible sources of inspiration
> 
> * https://github.com/AgeManning/discv5-cli
> * ...

I am going to work on since I want to be able to play with trin's RPC with a cli then writing code and using ``ethportal-api``

I made a issue to track it https://github.com/ethereum/trin/issues/730

**Comment by KolbyML** [comment]
We spoke on the call today and it seemed like the move is to remove ``trin-cli`` as a whole and move grafana to portalnet
