### ISSUE TITLE
Block header validity function 

### ISSUE THREAD

**Issue by jacobkaufmann** [ethereum/trin#59]
Implement the block header validity function defined in section 4.3.4 of the Ethereum Yellow Paper.

A node should perform basic block header validation to ensure that it only stores and transmits valid Ethereum block headers.

Without the accumulator, we cannot validate that a block is part of the canonical chain. Temporarily, we could make a request to Infura for a given block hash.

**Comment by njgheorghita** [comment]
Closing since this is being tracked in alpha testnet milestone ... and we're just using infura for now
