### ISSUE TITLE
NAT traversal

### ISSUE THREAD

**Issue by emhane** [ethereum/trin#596]
Optimised protocol based off https://github.com/ethereum/devp2p/issues/207
Relating to issue: https://github.com/ethereum/devp2p/issues/226

- [x] NAT hole punching: moved into: https://github.com/sigp/discv5/pull/176 from https://github.com/emhane/nat_hole_punch/tree/standardise-nat-hole-punch
- [x] Type up wire protocol for devp2p: https://github.com/ethereum/devp2p/pull/225
- [x] Type up theory for devp2p https://github.com/ethereum/devp2p/pull/228
- [x] Mechanism to keep hole punched for a peer, e.g. UTP stream.
- [x] _Remove sessions for peers that don't keep the hole punched for us after hole punching._ already default behaviour in the rust impl of discv5 for req time outs
- [x] Part 2 theory 'around the hole punching': https://github.com/ethereum/devp2p/pull/231
- [x] Make max total sessions with non-contactable enrs configurable (symmetrically NAT:ed, like nodes in many offices)
- [ ] Possibly also, look into predicting WAN reachable ports for peers behind symmetric NATs https://www.cs.cornell.edu/people/francis/fdna02-guha1.pdf https://netsec.ethz.ch/publications/papers/natblaster.pdf

**Comment by carver** [comment]
Work happening here: https://github.com/emhane/discv5/commits/nat-hole-punch

**Comment by emhane** [comment]
> Work happening here: https://github.com/emhane/discv5/commits/nat-hole-punch

Thanks Jason. Also here https://github.com/emhane/nat_hole_punch/tree/nat-hole-punch, and here for testing https://github.com/emhane/discv5-cli/tree/nat .

**Comment by carver** [comment]
When following the docs, I get this for the first server attempt:
```
error: Found argument 'query' which wasn't expected, or isn't valid in this context
```

I think it started up fine by just removing `query`. I haven't finished running the test, though.

**Comment by carver** [comment]
Hm, the second cli instance doesn't recognize `-u`, `-i`, or `-r`, so I sense that I'm doing something really wrong. I'm not seeing those options in `cargo run -p discv5-cli -- server -h`. I'm running commit aa52bbd2879c83257

**Comment by emhane** [comment]
But the latest commit at origin/nat is 8feb22ede3203e567bfcae4071f117c6eae472c0 ?

**Comment by carver** [comment]
yup, I'm a goof, that's why we post commit hashes! :P

**Comment by KolbyML** [comment]
After this is done we can look at closing this issue https://github.com/ethereum/trin/issues/22 since this would be the solution to it?

**Comment by emhane** [comment]
> After this is done we can look at closing this issue #22 since this would be the solution to it?

That's right, both issues tackle the same general problem of how to include nodes behind NAT in the network.
