### ISSUE TITLE
Persistence between runs without providing private key

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trin#621]
### What is wrong

Running the trin client in a manner that re-uses node-id and storage requires providing manual CLI args and is a barrier to entry.

### How can it be fixed.

I should be able to run the bare `./trin` binary without any additional arguments and it should:

- [x] default to the hardcoded bootnodes if none are explicitly provided
- [ ] generate a new private key for `node-id` if none exists.  Otherwise, it should re-use the previous one
- [ ] same for storage, lazily make a new one if needed, otherwise re-use.

**Comment by carver** [comment]
> same for storage, lazily make a new one if needed, otherwise re-use.

This should already be done, that trin will default to using the same storage directory, if you are reusing the same node id.

**Comment by pipermerriam** [comment]
I'm not likely to work on this anytime soon so I unassigned.

**Comment by carver** [comment]
Ah yes, in the pared-down project view of the issue, I didn't see the link to Nick's PR to see that he's the one who started in on it.

**Comment by KolbyML** [comment]
After this issue is solved we can potentially look at also closing this issue https://github.com/ethereum/trin/issues/320 since I believe it is generally targeting the same issue.
