### ISSUE TITLE
Cannot terminate process

### ISSUE THREAD

**Issue by victor-wei126** [ethereum/trin#65]
When I run `cargo run -p trin` it launches both state and history networks, but there is no way to cancel it. If you then try to run the state or history networks individually, like `cargo run -p trin-state`, it leads to a (non-terminating) error of code 98, "Address already in use". This is even after I already killed the previous process.

**Comment by ogenev** [comment]
I think this is because we are not handling properly SIGTERM signal when running both networks in parallel but I'm not sure if the current priority is to handle multiple networks simultaneously,

> it leads to a (non-terminating) error of code 98, "Address already in use". This is even after I already killed the previous process.

When you kill the process manually, you may need to also delete the jsonrpc IPC path too.
