### ISSUE TITLE
Add portal-hive test for post-Shapella headers

### ISSUE THREAD

**Issue by carver** [ethereum/trin#682]
- [x] Generate a post-Shapella header content key/value pair
- [ ] Post the value into the specs repo for other clients to test against
- [x] Add a new portal-hive test with the content

**Comment by ogenev** [comment]
`portal-hive` test added: https://github.com/ethereum/portal-hive/pull/29

**Comment by carver** [comment]
specs repo updated: https://github.com/ethereum/portal-network-specs/pull/208
