### ISSUE TITLE
Add `unwrap_used` lint warning to all workspaces

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#687]
From https://github.com/ethereum/trin/pull/681#discussion_r1173387002 it appears like we're not linting for naked unwraps in all workspaces.

### How to fix it?
Add `#![warn(clippy::unwrap_used)]` to `lib.rs` for any workspace that doesn't already contain this lint. Example: https://github.com/ethereum/trin/blob/master/trin-history/src/lib.rs. And handle any unwraps that might be lurking

**Comment by dhruvdabhi101** [comment]
I would like to contribute.

**Comment by Eren-Yeaager** [comment]
@njgheorghita  Hi ,I would like to contribute

**Comment by ogenev** [comment]
You are free to contribute, don't ask for permission :smile_cat: .
