### ISSUE TITLE
 `historyRecursiveFindNodes` endpoint takes too long to return a result

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trin#708]
### What is wrong

The default http client for the portal JSON-RPC API provided by the `ethportal-api` crate ends up with a timeout during most calls to `historyRecursiveFindNodes`

### How can it be fixed

I'm guessing there's a default timeout parameter that needs to be extended to allow the http request to hang longer waiting for the response....

**Comment by ogenev** [comment]
`ethportal-api` doesn't provide a default HTTP client,  it exposes API traits for the jsonrpsee HTTP clients to have information for all available endpoints.

Users of  `ethportal-api` are expected to create their own jsonrspee HTTP clients and they can set the timeout with [request_timeout](https://docs.rs/jsonrpsee-http-client/0.18.1/jsonrpsee_http_client/struct.HttpClientBuilder.html#method.request_timeout).

**Comment by pipermerriam** [comment]
I still think there's a fix needed here since it appears that the client defaults aren't sufficient to use the client with `trin`.  Which suggests that maybe the thing that needs to be fixed is the response times on the `historyRecursiveFindNodes` endpoint so that it reliably returns in under the default request timeout?

**Comment by KolbyML** [comment]
I am going to look into this since I am going through all the history RPC's anyways, @ogenev let me know if you want to look into it and that is fine.

I am going to implement history* ``add_enr``, ``get_enr``, ``delete_enr``, ``lookup_enr`` so I might as well also look into this

**Comment by KolbyML** [comment]
@pipermerriam Could you send a few lines of the log with that error? I am interested in what you get for the "x: *" the star part.
