### ISSUE TITLE
Rethinking Repository Structure, amid Release Planning

### ISSUE THREAD

**Issue by carver** [ethereum/trin#710]
## Plan?

TODO

## Background thoughts

When looking at our repository structure, and how crates are organized, I had thought that we could "vendor" one crate into another. It's possible to to *locally* use the source crate, but at the time of publishing any crate, we need each of the dependencies to be published too.

This personally alters my idea about what is a reasonable organizational structure. Some examples of what comes up for me:
 - `trin-types` was our internal implementation of types, and ethportal-api is our "external" one, but now they both have to be published anyway. Maybe we should just recombine them, with modules for what's meant to be internal and external?
 - `rpc` obviously is not a good name for a crate to be published externally. Maybe it should just be a module inside another crate
 - maybe `trin-core` was a better structure

Things that probably don't need to change are:
- `trin-cli` might go away anyhow, or never be published?
- `trin-bridge` feels like a different enough tool to be published separately

Even if we trim down the total number of crates, we will have a few left, and probably don't want to manage them independently. We probably want to use tools to help us avoid mistakes around releases. Ideally those tools would help us:
- build release notes for each released crate
- track whether a crate needs to have its version bumped
- bump and increase the version of the crate in all its dependent crates, as needed
- only publish crates that have changed since the last publishing
- publish all crates in dependency order, from a single command

At least one tool requires [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) to do a good job of auto-generating release notes.

Some example tools that might help us do this, either by combining their usage, or using a single tool that does everything:
- https://crates.io/crates/cargo-workspaces
- https://crates.io/crates/release-plz
- https://github.com/Byron/gitoxide/tree/main/cargo-smart-release
- https://github.com/crate-ci/cargo-release

**Comment by njgheorghita** [comment]
Hmm, well I wonder if this all is one of the reasons lighthouse doesn't publish their crates....

I won't be around tm for sync, but I'm somewhat against re-re-factoring. Each approach has tradeoffs, and it's not obvious to me that one set of tradeoffs significantly outweighs the other. So, I fall in the camp of let's just move forward and deal with a highly "regular" release cycle. Of course, a strong benefit that I'm missing for towards returning to a "trin-core"-esque structure could convince me otherwise.
