### ISSUE TITLE
Fix win-build circleci job

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#74]
In circle-ci runs, the `win-build` job doesn't run. Seems like we either need to add credits to carver's account or migrate this repo over to the ethereum org. @carver any thoughts?

<img width="1395" alt="Screen Shot 2021-08-13 at 1 23 55 PM" src="https://user-images.githubusercontent.com/9753150/129402886-0d460ac6-5867-4190-a4ad-c81d888342fe.png">

**Comment by KolbyML** [comment]
The credits reset in less then a week to my knowledge
