### ISSUE TITLE
low latency light overlays: k-peer-disjoint updates, scaling the p2p with bounded peer-updates 

### ISSUE THREAD

**Issue by emhane** [ethereum/trin#750]
Last year I started working on this [enr-bank-discv5](https://github.com/emhane/discv5/blob/148309cb8109f4ef28118063f89af4f8c6b866ad/src/service.rs#L212-L220), as I was researching on [Felix's topics spec](https://github.com/emhane/devp2p/blob/master/discv5/discv5-theory.md#topic-advertisement). The topics spec as well as Trin uses KBucket overlays, basically subsets of the discv5 network stored with respect to a different order, or in other words different partial views of the same network.
When the overlays overlap, ENR or connectivity updates that happen on one layer need to be visible on all overlays so that the overlays can scale efficiently. For example we can optimise memory usage and latency in the case of running more than one portal, like state and history, in the same instance as different top-level tasks, but also just running one portal on top of discv5 which very probably means a big overlap of peers between the discv5 DHT and the portal DHT already.
Currently, when a peer goes offline or updates their ENR, this needs to be found out anew by trial and error on each overlay - this latency, of 2 RTT for a PING-PONG ENR update and of 2 seconds for the default discv5 [query peer time out](https://github.com/sigp/discv5/blob/269b7f0fc73f85484b0c08929a8e7540ab5de20f/src/config.rs#L21-L24) upon unresponsiveness, can be minimised to once per peer - a constant bound, k = 1, on k-per-peer updates! Rn the per-peer updates  are bound by the input number of overlays. That takes a toll when we want to increase query parallelism and increase the number of virtualisation layers - portals of different services (not random) - on top of the discv5 DHT secured by random unstructured structure. So I suggest in terms of DHT entries we flatten all the layers of DHTs out, to one big pancake of k-bucket entries, with links from each entry to the DHT layers that includes the entry, as opposed to copies of the entry.
  
I have 2 different approaches in mind:
- If we don't have a memory constraint, we can add some [Discv5Event](https://github.com/sigp/discv5/blob/269b7f0fc73f85484b0c08929a8e7540ab5de20f/src/discv5.rs#L54-L76)s to know when a peer is disconnected
```rust
SessionDisconnected(NodeId),
```
and when an ENR of a peer is updated
```rust
EnrUpdated { enr: Enr, replaced: Option<Enr> },
```
We emit these events from _service.rs_ [here](https://github.com/sigp/discv5/blob/269b7f0fc73f85484b0c08929a8e7540ab5de20f/src/service.rs#L1338-L1340) and [here](https://github.com/sigp/discv5/blob/269b7f0fc73f85484b0c08929a8e7540ab5de20f/src/service.rs#L1317C24-L1319) respectively, and also [here](https://github.com/sigp/discv5/blob/269b7f0fc73f85484b0c08929a8e7540ab5de20f/src/service.rs#L1285-L1297) but first making the logic separation between connection update, value update and both updated (emit 2 events).

All `Discv5Event`s rn [clone the ENR](https://github.com/sigp/discv5/blob/269b7f0fc73f85484b0c08929a8e7540ab5de20f/src/service.rs#L1192) to thread-safely pass up to the app (move it) running discv5, which then stores the ENR in the app's k-buckets - if discv5 had space for the ENR in its k-buckets, it has also stored the ENR before passing it up.

- If we have a memory constraint: we use thread-safe references and locks. ENRs take up to 300 bytes in memory. Following [code snippets](https://github.com/sigp/discv5/blob/269b7f0fc73f85484b0c08929a8e7540ab5de20f/src/kbucket/bucket.rs#L102-L125) originate from kbucket/buckets.rs. How we lock  lock the `Node` depends on if we want to update connection status and the ENR independently. Locking the whole `Node`
```rust
pub struct KBucket<TNodeId, TVal: Eq> {
    /// The nodes contained in the bucket.
    nodes: ArrayVec<Arc<RwLock<Node<TNodeId, TVal>>>, MAX_NODES_PER_BUCKET>,
```
or, locking connection status and ENR independently
```rust
pub struct Node<TNodeId, TVal: Eq> {
    /// The key of the node, identifying the peer.
    pub key: Key<TNodeId>,
    /// The associated value.
    pub value: Arc<RwLock<TVal>>,
    /// The status of the node.
    pub status: Arc<RwLock<NodeStatus>>,
}
```
or if we can't make our mind up, with our current understanding of how we will use overlapping DHT overlays in the future, we make the whole node generic (definitely the best idea!), with traits so little of the existing code needs to be changed (i.e. so calls to methods of `NodeStatus` and `Node` types already in the code will still work).
```rust
pub trait AsNodeStatus {...}

pub trait AsNode<TNodeId, TVal: Eq, NodeStatus: AsNodeStatus> {...}

pub struct KBucket<Node: AsNode> {
    /// The nodes contained in the bucket.
    nodes: ArrayVec<Node, MAX_NODES_PER_BUCKET>,
```

This way each entry only exists once in memory, but can be mutated by any overlay. Any overlay can mutate any entry with just a read lock on the shared collection of all entries (the pancake) and that change will happen on all overlays, including the discv5 DHT: [check out my playground  example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0954e2513e65d69aaedc4ce7439dd735). Which is great when using a `RwLock` that allows for multiple concurrent reads. Without this lock on each entry, to disconnect a peer in discv5 based on some portal specific criteria requires waiting on a write lock [here](https://github.com/sigp/discv5/blob/269b7f0fc73f85484b0c08929a8e7540ab5de20f/src/discv5.rs#L231-L238).

Why would we have a memory constraint? The more efficiently portals or any other discv5 DHT overlay handles memory, the larger we can make k-buckets which in turn means me have more gains from increasing [query parallelisation](https://github.com/sigp/discv5/blob/269b7f0fc73f85484b0c08929a8e7540ab5de20f/src/query_pool/peers/closest.rs#L57-L60) to tackle latency. A memory-efficient way to increase k-buckets size is to handle [this interval](https://github.com/sigp/discv5/blob/269b7f0fc73f85484b0c08929a8e7540ab5de20f/src/kbucket.rs#L242) in at least two parts when [allocating memory for nodes ](https://github.com/sigp/discv5/blob/269b7f0fc73f85484b0c08929a8e7540ab5de20f/src/kbucket/bucket.rs#L125), where for example all buckets until log2distance 200 initialise with the current `MAX_NODES_PER_BUCKET`= 16 `ArrayVec<Node<TNodeId, TVal>, MAX_NODES_PER_BUCKET>` and all nodes log2distance 200 to 256 initialise allocating for 3 times as many nodes `ArrayVec<Node<TNodeId, TVal>, MAX_NODES_PER_BUCKET * 3>`. Tbh, the odds that even one single peer will be in the k-buckets aprox. log2distance 1-100 is so low, that imo we should change the data structure from `ArrayVec` to another data structure that doesn't allocate memory initially for that interval and dynamically allows that interval to allocate memory up to a `MAX_NODES_PER_BUCKET` limit. If no such data structure exists giving the option to set either a fixed or dynamic memory allocation, we could use an enum
```rust
enum Nodes {
    Fixed(ArrayVec),
    Dynamic(Vec),
}
```
and create a trait `AsArrayVec` with all the methods of `ArrayVec` called in the _kbucket/bucket.rs_, and then implement that trait for the enum `Nodes` to allow for easy compatibility with parity's existing k-buckets code (i.e. without changing the existing method calls).

(A related PR would be to remove [this event](https://github.com/sigp/discv5/blob/269b7f0fc73f85484b0c08929a8e7540ab5de20f/src/discv5.rs#L63-L64), which is not used anywhere in the code as [this method](https://github.com/sigp/discv5/blob/269b7f0fc73f85484b0c08929a8e7540ab5de20f/src/discv5.rs#L188-L229) and it's return type are sync.)

**Comment by 0xcrust** [comment]
Hey. I’d like to dedicate the next couple months to implementing this for the ethereum protocol fellowship if that’s fine with you

**Comment by emhane** [comment]
sure, @0xcrust. excuse the title confusion, was right the first time, k-peer-disjoint updates. peers overlapping in overlays are instances of the same peer and can be thought of as one vertex. overlays are (at least intentionally) unique. for sake of clarity some drawings...
terminal pairs $`(t_{1},s_{1}),...,(t_{k},s_{k})`$ are overlays. each overlay is a tuple of its binary tree of peers (DHT) before an update contracted into one vertex $`t_{i}`$ and after an update contracted into one vertex $`s_{i}`$. inner vertices are peers being updated and paths between terminal pairs are update operations.
<img width="428" alt="current-overlays" src="https://github.com/ethereum/trin/assets/58548332/5b6ce558-a8d2-404c-bfc0-972c3120c4fe">
rn this happens. for each terminal pair, that is for each overlay containing the peer to update, an update operation happens. for example to update peer $`v_{1}`$ which is contained in all overlays a path passes through $`v_{1}`$ for each overlay. in other words there aren't disjoint paths to update a peer that appears in more than one overlay.
<img width="428" alt="scalable-overlays" src="https://github.com/ethereum/trin/assets/58548332/1237b0c2-5c11-4de8-905b-ca4be9d1dd53">
this is what we want to do. merge the set of peers in all overlays into one so that we are left with only one pair of terminals which is in effect $`(\bigcup\limits_{i=1}^{k} t_{i},\bigcup\limits_{i=1}^{k} s_{i})`$, a pool of all peers, then have symbolic links via rust's `Arc<T>` type from overlays to a peer in that pool. this way we have one disjoint path per updated peer, following trivially from having only one terminal pair. so to be precise, the above drawing is showing the solution for the problem for 3 peers.

what data structure to use for the peer pool is up to you. it could be a DHT too, but then indexing peers could get tricky if in one overlay we want to measure distance relative to another node id than the local node id. a hash map is a future proof choice.

**Comment by 0xcrust** [comment]
Hey. Sorry about the late reply. It took a while before I felt like I knew enough to give any reasonable response to this.

I linked a draft pr to make the types in the discv5 crate generic over the node type. It currently does not make a separation between locking the ENR and connection status though.  If that's still a recommendation then I can add a commit to make that possible.

I do understand your proposal now, thanks for the detailed explanation. I'm not sure I follow the last statement though and why that is a potential issue. Wouldn't each overlay still maintain their distinct k-buckets structure, with the only change being that each of its nodes would be a shared reference?
