### ISSUE TITLE
ethportal-api: Add base RPC endpoints for State network

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#753]
Include base RPC endpoints for the State network in `ethportal-api`. [Here](https://github.com/ethereum/trin/blob/master/ethportal-api/src/history.rs) is a history network example of what we also want to implement for the State at this stage.

**Comment by KolbyML** [comment]
I was planning to do this after https://github.com/ethereum/trin/pull/742 was merged, since I want to start playing with the state network.

Would I be fine still doing this or should we let someone who hasn't contributed before work on it?

**Comment by ogenev** [comment]
> Would I be fine still doing this or should we let someone who hasn't contributed before work on it?

I would start with https://github.com/ethereum/trin/issues/752 which seems more interesting and will help us add the state endpoints implementations in the `trin-state` crate.

**Comment by KolbyML** [comment]
> > Would I be fine still doing this or should we let someone who hasn't contributed before work on it?
> 
> I would start with #752 which seems more interesting and will help us add the state endpoints implementations in the `trin-state` crate.

Ok I will attempt to work on #752

**Comment by EastVoice1** [comment]
wow thisi crazy let me in

**Comment by KolbyML** [comment]
This was implemented by Milos https://github.com/ethereum/trin/pull/1175
