### ISSUE TITLE
Update trin's validation strategy

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#755]
Following up with our recent discussion in weekly stand, we decided to update trin's validation strategy. 

### Step 1
Remove all dependence upon Infura / external provider to validate content data. Essentially this consists of removing the `TrustedProvider` type.

### Step 2
A cli flag that the user can set to choose the level of data validation that occurs within `HeaderOracle`
- `--validation strict` - the default setting. 
  - this attempts to validate all content by fetching validation data from the network. it will only return data that is successfully validated
- `--validation loose` 
  - return content that passes validation & also in the case where we are unable to acquire the data from the network required to validate the content
- `--validation none`
  - return all content retrieved from the network, regardless of validation

**Comment by KolbyML** [comment]
> * `--validation loose`
>   
>   * return content that passes validation & also in the case where we are unable to acquire the data from the network required to validate the content

what do you mean by "also in the case where we are unable to acquire the data from the network required to validate the content"

Does it mean this flag will allow us to return data we validated, but also data we didn't?

Wouldn't that then be the same as none though since non will return both validated and non-validated data.

**Comment by njgheorghita** [comment]
Tbh, I'm not convinced this is the ideal strategy that we want to support, so I'd wait until we get some other team members to chime in on how we want to build this out...

> Wouldn't that then be the same as none though since non will return both validated and non-validated data.

Almost the same, the only difference is that `loose` will **not** return data that has been invalidated. `none` will return any and all data retrieved from the network. Again, not even sure if this is something we want to support?

**Comment by njgheorghita** [comment]
Actually, now that I'm thinking about it a bit more. It seems likely that a `none` flag could be useful in particular for debugging network data.

**Comment by njgheorghita** [comment]
Closing this since we've adopted a de facto "strict" validation policy
