### ISSUE TITLE
Websocket port should be configurable via cli arguments

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#764]
https://github.com/ethereum/trin/pull/757#discussion_r1219642958

**Comment by ogenev** [comment]
HTTP and WS must run on a separate port.  Current defaults are 8545 for HTTP and 8546 for WS.

**Comment by njgheorghita** [comment]
Following up ^ - it appears as though all of this logic should also be removed... https://github.com/ethereum/trin/blob/master/rpc/src/rpc_server.rs#L385-L425

**Comment by tesol2y090** [comment]
Hi, i would like to take this issue but i seem like in cli arguments, there are --ws-port already.

**Comment by morph-dev** [comment]
I think you are correct and this was already implemented in #992 , but issue was never closed.
