### ISSUE TITLE
fully remove wrapped NodeId with native discv5 type tracking PR

### ISSUE THREAD

**Issue by KolbyML** [ethereum/trin#770]
After this PR is merged https://github.com/sigp/enr/pull/34 a new discv5 release is out. We can fully remove our wrapped NodeId instance, currently the last place it is used is in our query tracing code.

This is because
> Without adding serde(with = "SerHex::<StrictPfx>") if you tried to
> 
> ```rust
>         let mut responses: HashMap<NodeId, u16> = Default::default();
>         responses.insert(discv5::enr::NodeId::random(), 1);
>         let hi = json!(responses);
> ```
> 
> json!(...) will fail with `"key must be a string"`

**Comment by ogenev** [comment]
@KolbyML should we close this issue as completed?

**Comment by KolbyML** [comment]
closed by https://github.com/ethereum/trin/pull/800
