### ISSUE TITLE
Implement --ephemeral flag

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#81]
When testing internal p2p network calls, we would like to be able to run multiple node instances simultaneously.
To avoid db folder collusion, we want to set unique db folder name for every node id.

As a default db folder, current implementation is using last 8 characters of base64 encoded `Enr` appended to the application name:
https://github.com/carver/trin/blob/d99232fd43c8dd0ec055150f382546cbba747bef/trin-core/src/utils.rs#L58

It will be better, if we change this to append the first few characters (instead of last 8) of the as-displayed node-id to the application name.

**Comment by mrferris** [comment]
What's the reasoning for using the first 8 instead of last 8?

**Comment by ogenev** [comment]
> What's the reasoning for using the first few instead of last 8?
> 
> Now that I ask I'm guessing it's because the beginning part is more easily comparable by eye, like with git commit hashes.

Yeah, it is related to Jason's comment [here](https://github.com/ethereum/trin/pull/80#discussion_r694203573).

**Comment by hmrtn** [comment]
PR #277 is ready for review 👍
