### ISSUE TITLE
`ethportal_api::HistoryContentValue::decode()` fails to decode block bodies 

### ISSUE THREAD

**Issue by mrferris** [ethereum/trin#815]
This is happening on trin when receiving block bodies from the testnet using `ethportal_api v0.2.0`.

Block bodies are successfully received over utp, but when passed to `ethportal_api::HistoryContentValue::decode()` a `ContentValueError::UnknownContent` is thrown [from here](https://github.com/ethereum/trin/blob/2fff9ffd7cc87788ecc103aa0fbad72adc9af7f0/ethportal-api/src/types/content_value/history.rs#L114).

An example of a hex-encoded block body response that this happens with [is here](https://gist.github.com/mrferris/34e35ab9675094a4fc3ec868574ba856) (see below for another example with a known block number).

It appears to be ~143 kB of data.

Block bodies that produced this failure were received from both trin (90% sure, based off using port 9000) and a client that was using port 18499. tbd which client that was.

Receipts do make it through decoding successfully, so I think that the encoding/decoding of block bodies is to blame rather than other code involved, such as utp or the code using `ethportal_api`, which in this case is glados. 
```[tasklist]
### Tasks
- [ ] reproduce in portal hive
```

**Comment by njgheorghita** [comment]
Do you know what block number the body is from?

**Comment by mrferris** [comment]
> Do you know what block number the body is from?

Here is what's supposed to be the block body for block 17,889,645, but failing decode:

https://gist.github.com/mrferris/b28b43c9df4ef9ce3c2a89714d14f72d

**Comment by njgheorghita** [comment]
@mrferris Where is the code in glados that's decoding this? I'm able to succesfully call `BlockBody::from_ssz_bytes(&raw_bytes).unwrap();` on the value linked above

**Comment by njgheorghita** [comment]
nvm just saw it in the description 🤦

**Comment by njgheorghita** [comment]
looks like glados is still using `ethportal-api = 0.2.0` [here](https://github.com/ethereum/glados/blob/master/glados-monitor/Cargo.toml#L24) - maybe updating to `0.2.1` will fix this issue?

**Comment by carver** [comment]
reth issues might be related to https://github.com/ethereum/trin/pull/833

**Comment by mrferris** [comment]
Closing, solved by releasing new `ethportal-api v0.2.1`
