### ISSUE TITLE
Bug: "Error receiving content ... error=oneshot canceled"

### ISSUE THREAD

**Issue by carver** [ethereum/trin#821]
> 2023-08-04T01:18:47.445374Z  WARN portalnet::overlay: Error receiving content from service protocol=History error=oneshot canceled content.id=0x79ba16c1c2bac068f5ccfb4dd72f2f39fd06434007fbc7c5fdb9bb2da958b7c2

Produced here (and seen in practice): https://portal-hive.ethdevops.io/viewer.html?file=results/trin/client-236f41433a53c24c88097f7d553655ef24769cc31cb2d267b5b318b09f51852f.log

Some to-dos:
- [ ] what exactly is happening?
- [ ] can we log something that more clearly explains the situation?
- [ ] it's causing an actual bug in portal-hive, how can that be prevented? (somewhat orthogonal)

**Comment by KolbyML** [comment]
@carver yes and I am looking into why FC and RFC are timing out on a uTP transfer

**Comment by KolbyML** [comment]
This issue can be closed after https://github.com/ethereum/trin/pull/825 is merged
