### ISSUE TITLE
Add event communication mechanism between overlays

### ISSUE THREAD

**Issue by 0xcrust** [ethereum/trin#826]
> An idea I had. Feedback would be very much appreciated. I'm willing to send in a PR if this is something you're welcome to including.

It seems to me like there could be some benefit to overlays having the ability to communicate with each other. For example, this might mean that an overlay can send connection updates to other overlays for them to handle if it concerns them.

An example implementation could be to make the overlay event-stream a broadcast channel, and let the `PortalnetEvents` handler hold optional receive handles to each of the overlays it holds. It would then be able to dispatch those events in form of OverlayCommands to other overlays.

Open to feedback!

**Comment by ogenev** [comment]
I think this is worth exploring. We still don't know all the use cases for a network to communicate with another network. 
What we know for now is that we will need data from the beacon network to verify post-merge headers in the history network.

 In this scenario, we can use a validation service (refactored version of the current `HeaderOracle`) as a bridge between the networks or we can allow a network to make requests to another network.

**Comment by 0xcrust** [comment]
I hadn't come across the HeaderOracle initially. I just took a look and it seems to already set out a template for inter-overlay communication. I still think though that it might be worth consideration to not rope this in with validation logic, which serves a specific use-case.

I was thinking of a design that makes use of the existing overlay `event stream` channel, but tweaks it such that it gives out multiple subscriber handles. The `Portalnets` event handler can subscribe to the event-streams of each of the overlays it manages, and potentially dispatch an event it receives to overlays that it might concern.

Potential use-cases are overlays communicating enr-updates/session-disconnection events between them, as is mentioned in #750

**Comment by ogenev** [comment]
> I hadn't come across the HeaderOracle initially. I just took a look and it seems to already set out a template for inter-overlay communication. I still think though that it might be worth consideration to not rope this in with validation logic, which serves a specific use-case.

I agree that it is best to not rope this in with validation logic and I'm :+1:  for experimenting with what you propose.

**Comment by ogenev** [comment]
Resolved in #903.
