### ISSUE TITLE
Queue accepted content

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#856]
# Problem
Currently, when `trin` handles an `OFFER` message, it cycles through every offered `content_key` and checks with storage if [the key is within radius and not already present in the data store](https://github.com/ethereum/trin/blob/master/portalnet/src/overlay_service.rs#L1194-L1209). This strategy ignores content keys that have already been "accepted" but are still being transported over utp. This can lead to a node initiating multiple utp streams with different peers for the same content key.

Given the relatively small size of our network, it seems quite reasonable that our bridge nodes will be offering the same content key (eg. `latest`) to the same node in a relatively short timeframe. Due to the large size of some of these content values (eg. bodies/receipts), a node might accept the same content key from each bridge node before it has a chance to complete a single utp transfer & store the content value. 

Running multiple utp streams for the same content key adds bloat to the network. 

### Sidenote
While running trin, it's fairly common that I've seen the [Accepted content outside radius or already stored](https://github.com/ethereum/trin/blob/master/portalnet/src/overlay_service.rs#L1637C34-L1637C83) log, which is a solid indicator to me that we are duplicating our accepted content keys. 

# Solution
For the sake of this issue, a content key is considered in "processing" from the instant it is `Accepted` until the moment it is saved into local storage. This covers the timeframe that it takes to transport the actual content and validate it. This can take some time depending on how large the content value is or how many network requests are needed to fetch the relevant validation data. 

Introduce some kind of queue to the `OverlayService` that maintains a record of every content key which is currently "processing".

The order of operations for deciding whether or not to `Accept` an `Offer`ed content key looks something like this...

1. Check with storage if key is within radius & not already present in the data store (same as before).
2. Check with the queue if the content key is currently "processing"
  A. If yes, respond to the `Offer` that we do not want to `Accept` this content key.
  B. If no, save it as "processing", and respond to the `Offer` that we want to `Accept` this content key. 
3. After successful "processing" or if any step of "processing" fails we want to be sure we clear the content key from the queue.

This is the simplest solution I can think of, and certainly not optimal. But it seems to me like starting with the simplest solution is best. 

### Possible Improvements
- Trigger a recursive find content lookup if any step of "processing" fails. 
- Store the peer's enr in the queue for all content keys that go to step 2A, so that if "processing" fails we can send that peer a `FindContent` request, with a relatively high degree of confidence that they will have that content

**Comment by 0xcrust** [comment]
Hello. I would like to take this one on
