### ISSUE TITLE
Create RoutingTableInfo type

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#862]
Not sure why, but we [use a simple `Value` as the data type for the type alias `RoutingTableInfo`](https://github.com/ethereum/trin/blob/01b7d4ef03ed5297d0c72f42fd403d7aa6d7671f/ethportal-api/src/types/discv5.rs#L30). We should implement an actual `RoutingTableInfo` struct, that serializes & deserializes according to the [specified return type](https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/ethereum/portal-network-specs/assembled-spec/jsonrpc/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView%5D=false&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false).

**Comment by 0xcrust** [comment]
Hello. I'd like to take this one
