### ISSUE TITLE
ethportal-peertest: Move all constant hexstr content to load from yaml files

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#866]
We store history content hexstr data in the `ethportal-peertest/src/constants.rs` file as strings:

https://github.com/ethereum/trin/blob/01b7d4ef03ed5297d0c72f42fd403d7aa6d7671f/ethportal-peertest/src/constants.rs#L64

 We want to load those strings from yaml files instead.

**Comment by KaydenML** [comment]
I fixed this issue in this PR
PR: https://github.com/ethereum/trin/pull/1130
