### ISSUE TITLE
Create Flamingo Grafana dashboard

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#870]
When pushing new releases to the network, it would be useful to have a flamingo-centric dashboard that displays all of the data that would be useful for the flamingo to understand how the network health was affected after the deployment. Right now the flamingo needs to click into every node to evaluate how a node is behaving. So a dashboard that aggregates & displays a few important metrics from every node would be great. As well as distinguishing between bridge / boot / backfill / regular / etc. nodes.

**Comment by carver** [comment]
grafana was updated
