### ISSUE TITLE
`web3_clientVersion` displays `trin-utils` version

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#878]
When we want to get the client version, we use the `CARGO_PKG_VERSION` env variable to display the version metadata from the `Cargo.toml` file.

https://github.com/ethereum/trin/blob/633e53bd1464538ce984b14082b86f289ff9026e/trin-utils/src/version.rs#L1

This is fine as long as we call the env from the correct package :smile_cat: .
 In the example above, `CARGO_PKG_VERSION` returns the version of the `trin-utils` package, not the version of the `trin` package. 
 So any changes made to `trin/Cargo.toml` version have no effect on the `web3_clientVersion`  endpoint.

**Comment by AmirH-A** [comment]
This problem has been solved, if you think it is advisable to close the issue
