### ISSUE TITLE
Fix `uint v0.4.1` compile warning

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#881]
On compiling the Trin workspace we get the following warning:

`warning: the following packages contain code that will be rejected by a future version of Rust: uint v0.4.1`

This can be fixed when we switch to [eth_trie.rs](https://github.com/carver/eth-trie.rs) v0.3.0` after this [PR](https://github.com/carver/eth-trie.rs/pull/31) is merged and the new version is released.

**Comment by carver** [comment]
v0.3.0 of eth_trie.rs is released!
