### ISSUE TITLE
Prevent build warnings in portal-hive, using CI

### ISSUE THREAD

**Issue by carver** [ethereum/trin#883]
When I run a cargo build locally, I get this warning:
```
error: variable does not need to be mutable
   --> /home/carver/code/portal-hive/hivesim-rs/src/testapi.rs:202:17
    |
202 |             let mut test = &mut Test {
    |                 ----^^^^
    |                 |
    |                 help: remove this `mut`
    |
    = note: `-D unused-mut` implied by `-D warnings`
```

It seems like the CircleCI configuration isn't correctly checking for warnings.

**Comment by njgheorghita** [comment]
Seems to me like this issue belongs in the [portal-hive](https://github.com/ethereum/portal-hive) repo?

**Comment by KolbyML** [comment]
We already handle this. Portal-Hive was just using rust 1.68 which didn't support this clippy check yet my PR for bridge-tests updates the version of rust and hence this shows up in CI.

**Comment by KolbyML** [comment]
I'm closing this as https://github.com/ethereum/portal-hive/pull/87 I updated the rust version in this PR and hence CI now picks update the new clippy changes from the newest version
