### ISSUE TITLE
Support for eth_getBlockByHash RPC endpoint, in post-Shanghai blocks

### ISSUE THREAD

**Issue by carver** [ethereum/trin#884]
The following is a necessary, but probably not sufficient, list of tasks to finish this issue.

```[tasklist]
### Sub-components
- [ ] https://github.com/ethereum/trin/issues/885
- [ ] #279
- [ ] Return fully-decoded transactions if specified in eth_getBlockByHash request
```

**Comment by njgheorghita** [comment]
I guess my assumption was that with the transition away from a user-facing wallet, we were leaving the `eth_*` jsonrpc methods behind, and no longer targeting their support. Based on this issue it seems like we're targeting **partial** support of the standard jsonrpc api?

Just to play devils advocate here, why not drop the `eth_*` namespace entirely for now, and require users to use the `portal_*` api? Our "users" initially are client devs, and I think it's reasonable to expect them to interact w/ the portal network via our native jsonrpc api. In fact, exposing partial support for `eth_*` api endpoints might be a bit confusing, and opaquely disguise what kind of data is actually available on the network.

**Comment by carver** [comment]
Ah, so yeah I think we still want to support the `eth_*` namespace. Although we can't serve the endpoints fast enough to be a good backend for a wallet, there's nothing stopping us from serving them slowly. Even if it's mostly used by researchers, etc, they probably still prefer to get access using the known endpoints, instead of a new `portal_*` namespace. The endpoints are familiar, and there is a lot of tooling built around them (like in web3 libraries).

If you're not convinced, it's definitely worth a chat in a trin meeting when you get back.
