### ISSUE TITLE
Portal history bridge should not panic on error

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#893]
When we experience an error serving the latest history data, we immediately panic due to this line:

https://github.com/ethereum/trin/blob/413bfd47fb3edcfb01c99c785ac108976811ca8e/portal-bridge/src/bridge.rs#L120C53-L120C53

The history bridge should not panic on errors (including when the pandaops nodes are experiencing issues) and we should keep trying to request the new data every block.

**Comment by KolbyML** [comment]
Closing as this is no longer a problem in the current state of the bridge
