### ISSUE TITLE
Performance issues : Found occurrence of Arc<RwLock<HashMap<K, V>>>

### ISSUE THREAD

**Issue by philipjonsen** [ethereum/trin#914]
DESCRIPTION

Arc<RwLock<HashMap<K, V>>> has performance concerns, the dashmap crate provides a much better alternative to concurrent hashmaps. Hence, Arc<RwLock<HashMap<K, V>>> is better off replaced by Arc<DashMap<K, V>> from the dashmap crate.

BAD PRACTICE

struct Bar<K, V> { foo: Arc<RwLock<HashMap<K, V>>> }

RECOMMENDED

struct Bar<K, V> { foo: Arc<DashMap<K, V>>> }

REFERENCES

[dashmap](https://crates.io/crates/dashmap)

Find it here:

Using under performant concurrent hashmap, RwLock<HashMap<K, V>>, consider using the dashmap crate

[portalnet/src/overlay_service.rs](https://github.com/philipjonsen/trin/blob/master/portalnet/src/overlay_service.rs#L281-L281)

    /// This is used internally to submit requests (e.g. maintenance ping requests).
    command_tx: UnboundedSender<OverlayCommand<TContentKey>>,
    /// A map of active outgoing requests.
    active_outgoing_requests: Arc<RwLock<HashMap<OverlayRequestId, ActiveOutgoingRequest>>>,
    /// A query pool that manages find node queries.
    find_node_query_pool: Arc<RwLock<QueryPool<NodeId, FindNodeQuery<NodeId>, TContentKey>>>,
    /// A query pool that manages find content queries.

**Comment by mrferris** [comment]
Will re-open if any evidence is shown that the `active_outgoing_requests` hashmap is a performance bottleneck in trin
