### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by KolbyML** [ethereum/trin#917]
- [x] Add windows support (making windows not build ipc code)
- [x] Add minimalist CI to make sure it compiles (we don't have to do a test CI since we already do that with linux)
- [x] Add windows build instructions
- [x] Add windows cross compilation instructions
- [ ] Manual test of running trin on Windows

**Comment by carver** [comment]
> * Add minimalist CI to make sure it compiles

I'm good with that as a target for this issue, glad you added it 👍🏻 

> we don't have to do a test CI since we already do that with linux

Over time, I expect this to be less true, generally. For example, we probably want to implement IPC on Windows using NamedPipes, eventually. Then we would want to test functionality in both platforms. But that would be part of an issue adding IPC support for Windows.

**Comment by KolbyML** [comment]
Windows does support linux IPC, but yeah NamedPipes is a good option since rust libraries already support and they don't support Windows linux IPC.

**Comment by carver** [comment]
> Windows does support linux IPC, but yeah NamedPipes is a good option since rust libraries already support and they don't support Windows linux IPC.

Right, my point was less about how exactly we'll implement IPC, and more about how we will actually want to run a separate test run in a Windows environment, in order to get coverage of those unique code paths needed to run on Windows.
