### ISSUE TITLE
--ephemeral should use a non-default port

### ISSUE THREAD

**Issue by carver** [ethereum/trin#919]
If a port isn't explicitly specified, and the `--ephemeral` flag is set, then we should set a different port.

The main annoyance of using the default port is if you use `--ephemeral` twice in a row, or run ephemeral and then a non-ephemeral run. Because a bunch of former peers are contacting you on that port, expecting a different public key, your logs get flooded with warnings about incoming packets that can't be decoded. (This happened on Joseph Cook's first contact with trin)

Maybe chose the port based on the generated node-id, to help spread it out across runs? Maybe randomize the port?

**Comment by 1010adigupta** [comment]
I can take up this, you can assign me

**Comment by KaydenML** [comment]
Fixed this issue in this PR
https://github.com/ethereum/trin/pull/1124

**Comment by KolbyML** [comment]
There was a PR open to fix this issue for 10 months. It wasn't reviewed due to lack of interest so I am closing this issue. If a member of the team is interested in this issue, https://github.com/ethereum/trin/pull/1124 should be reviewed and merged
