### ISSUE TITLE
Subnetwork overlay protocols implementation

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#93]
- How are the subnetwork overlay discv5 protocols instantiated?
- What responsibilities does the orchestrator have, and what is needed in each subnetwork initialization to kick off their overlay networks?
- If a user runs a subnetwork as a solo binary, will it still work?

**Comment by carver** [comment]
>     * How are the subnetwork overlay discv5 protocols instantiated?

A first guess: `PortalnetProtocol` becomes split into `StatePortalProtocol::new(discovery, portalnet_config)` and `HistoryPortalProtocol::new(discovery, portalnet_config)`. `discovery` is instantiated in the main `trin` and passed to any subnet init. That way, discovery is run once and directly used by each subnet.

**Comment by ogenev** [comment]
> A first guess: `PortalnetProtocol` becomes split into `StatePortalProtocol::new(discovery, portalnet_config)` and `HistoryPortalProtocol::new(discovery, portalnet_config)`. `discovery` is instantiated in the main `trin` and passed to any subnet init. That way, discovery is run once and directly used by each subnet.

This makes sense, I will take a stab to prototype something and encapsulate the logic for the different networks.

**Comment by njgheorghita** [comment]
I've also been working on this - but happy to pass it off to you. My understanding of the overlay networks was not so great, but here are some things I've been thinking about / learned that might be a factor in your implementation. I'm not sure how helpful/redundant this is, but writing it down just in case. @pipermerriam please correct me wherever I'm wrong, or fill in the gaps if I missed something.
- All that is needed to initialize a subnetwork discovery protocol is...
   - bootnodes. These can be the same bootnodes used by the base discovery, or it can be subnetwork-specific bootnodes passed in via cli. 
   - a channel to the base discovery protocol that can be used to pass/receive inbound/outbound messages. 
- Subprotocol routing tables are essentially independent from the base routing table. They are responsible for their own [bootstrapping](https://notes.ethereum.org/8LbisMwtR4yK64SBosb_2g#E1a---Bootnodes) / [population](https://notes.ethereum.org/8LbisMwtR4yK64SBosb_2g#E2---Population-of-routing-table) / [liveliness checks](https://notes.ethereum.org/8LbisMwtR4yK64SBosb_2g#E1a---Bootnodes)
- Some subnetworks (in particular state) will use a custom distance function, different from that of the base discovery
- Base & subnetwork routing tables will run independently, but they will share the same ENR db. All discovery protocols (base & subnetwork) are responsible for updating this ENR db with the latest known ENRs for their respective node id.
- We only want to run discovery over a single udp socket. All subprotocol discovery (ping/pong/findnodes/foundnodes) get wrapped up in `TALKREQ`/`TALKRES` messages and dispatched via the base discovery protocol.

**Comment by ogenev** [comment]
Hey @njgheorghita , I didn't know you are working on this, I can pick something else if you want.

**Comment by njgheorghita** [comment]
Yeah no worries at all. I didn't assign it to myself. I'm happy to pass it off to you if you'd like to tackle it. Another option is maybe you tackle an implementation for `trin-history` and I'll go for `trin-state` - then we can compare approaches? That should yield a nice implementation, but obvs involves some duplicate work. What do you think?

**Comment by pipermerriam** [comment]
> - All that is needed to initialize a subnetwork discovery protocol is...
>   - bootnodes. These can be the same bootnodes used by the base discovery, or it can be subnetwork-specific bootnodes passed in via cli.

Clarification: The sub-protocol bootnodes **must** be nodes that speak the sub-protocol.  A sub-protocol bootnode can always be a bootnode for the base protocol.  A base protocol bootnode will not always be a viable sub-protocol bootnode (because they may not actually speak the sub-protocol)

**Comment by ogenev** [comment]
> Yeah no worries at all. I didn't assign it to myself. I'm happy to pass it off to you if you'd like to tackle it. Another option is maybe you tackle an implementation for `trin-history` and I'll go for `trin-state` - then we can compare approaches? That should yield a nice implementation, but obvs involves some duplicate work. What do you think?

Cool, works for me, there is some refactoring to be done for the Discovery struct which may overlaps, but I'm ok with it.
