### ISSUE TITLE
uTP log level not useful

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#938]
When running Trin with `info` log level, I'm getting some uTP log errors and warnings that I, as a user, can't do anything about them and this doesn't interfere with my work with the node:

![Screenshot_20230928_121713](https://github.com/ethereum/trin/assets/39865181/0f9d809b-33d4-4394-9609-c47f961abc23)

I think end users should not care if some of the uTP streams fail as long as this doesn't break the general usage of the node.

I propose to downgrade those log messages to `debug`/`trace` .

**Comment by KolbyML** [comment]
Yep that sounds like a good change

**Comment by njgheorghita** [comment]
fixed in #1000
