### ISSUE TITLE
Trin's query success rate degrades after running for 24+ hours

### ISSUE THREAD

**Issue by mrferris** [ethereum/trin#946]
For example, yesterday glados was showing trin finding content 95% successfully. This morning it had dropped to 80%. After restarting trin the success rate climbed back north of 90%. This pattern is consistent.

Things to check degradation:

- [ ] routing table contents (are we losing/disconnecting from too many nodes?) 
- [ ] utp success rates

**Comment by njgheorghita** [comment]
Imo this can be closed, since it seems like the utp bug for generating connection ids was the primary culprit in this scenario, and that has been fixed.
