### ISSUE TITLE
Portal bridge should guarantee that data was successfully bridged

### ISSUE THREAD

**Issue by mrferris** [ethereum/trin#962]
Portal bridge cannot currently provide either information nor guarantees about how many nodes successfully received the bridged content. 

Trin's `propogate_gossip` function (which is used by portal bridge) is not aware of how many populated `ACCEPT` messages were received by trin in response to the `OFFER` messages that it sends, nor how many resulting uTP streams succeeded.

**Comment by njgheorghita** [comment]
This was resolved in #1032
