### ISSUE TITLE
Trin should gossip content before it drops it from storage

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#981]
A possible enhancement came to mind during a recent chat with @carver that it would be worthwhile to gossip content as it gets dropped from storage. This won't help in situations when the network is over capacity, but in all other situations it should help maintain data availability in the network, as new nodes might have recently come online that would be interested in the data.

**Comment by pipermerriam** [comment]
I love this.  Seems like it belongs in a section of the specs that would be focused on best practices for client implementations.
