### ISSUE TITLE
shortcomings of current portal_historyTraceRecursiveFindContent implementation

### ISSUE THREAD

**Issue by mynameisdaniil** [ethereum/trin#987]
I've been trying to implement `portal_historyTraceRecursiveFindContent` for fluffy and here's what I've found on my journey:
- fields mostly `snake_case` while everywhere else in the RPC they are `camelCase`
- `port` and `ip` in `metadata` are redundant since this info contained in the ENR
- `distance` in the `metadata` is obviously clipped, cause it can be up to 256 bits and JSON integer can only be 53 bits. It should probably be encoded into hex string.
- `distance_log2` is redundant, we already have distance
- `started_at` is never used in the glados.

Here's spec update that addresses this improvements: https://github.com/ethereum/portal-network-specs/pull/236
And here's glados PR that supports this change: https://github.com/ethereum/glados/pull/177

**Comment by njgheorghita** [comment]
> started_at is never used in the glados.

Just because it's not yet used, I'm not sure that means it won't be useful. @mrferris if I remember correctly, you were the one who put this together initially? Do you remember what the purpose was for including the `started_at` field? Do you think it's something we should leave in, or is it safe to remove?

**Comment by mrferris** [comment]
Yea, let's leave `started_at` (as `startedAt`), glados should be updated to use it.

Agreed on all other points. Some were due to shortcomings of the parsing on the front end that @mynameisdaniil has fixed in [this PR](https://github.com/ethereum/glados/pull/177).
